//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class HomeOpsApiClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    health(): Promise<void> {
        let url_ = this.baseUrl + "/health";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHealth(_response);
        });
    }

    protected processHealth(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    getEventSources(): Promise<EventSource[]> {
        let url_ = this.baseUrl + "/api/event-sources";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetEventSources(_response);
        });
    }

    protected processGetEventSources(response: Response): Promise<EventSource[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(EventSource.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<EventSource[]>(null as any);
    }

    getAgendaLayerSettings(deviceKey: string | null | undefined): Promise<AgendaLayerSettingsDto> {
        let url_ = this.baseUrl + "/api/agenda/layer-settings";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "X-HomeOps-Device-Key": deviceKey !== undefined && deviceKey !== null ? "" + deviceKey : "",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAgendaLayerSettings(_response);
        });
    }

    protected processGetAgendaLayerSettings(response: Response): Promise<AgendaLayerSettingsDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AgendaLayerSettingsDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AgendaLayerSettingsDto>(null as any);
    }

    saveAgendaLayerSettings(deviceKey: string | null | undefined, request: SaveAgendaLayerSettingsRequest): Promise<AgendaLayerSettingsDto> {
        let url_ = this.baseUrl + "/api/agenda/layer-settings";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "X-HomeOps-Device-Key": deviceKey !== undefined && deviceKey !== null ? "" + deviceKey : "",
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSaveAgendaLayerSettings(_response);
        });
    }

    protected processSaveAgendaLayerSettings(response: Response): Promise<AgendaLayerSettingsDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AgendaLayerSettingsDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AgendaLayerSettingsDto>(null as any);
    }

    getLists(): Promise<ListSummaryDto[]> {
        let url_ = this.baseUrl + "/api/lists";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLists(_response);
        });
    }

    protected processGetLists(response: Response): Promise<ListSummaryDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ListSummaryDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ListSummaryDto[]>(null as any);
    }

    createList(request: CreateListRequest): Promise<ListDto> {
        let url_ = this.baseUrl + "/api/lists";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateList(_response);
        });
    }

    protected processCreateList(response: Response): Promise<ListDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = ListDto.fromJS(resultData201);
            return result201;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ListDto>(null as any);
    }

    getListById(listId: string): Promise<ListDto> {
        let url_ = this.baseUrl + "/api/lists/{listId}";
        if (listId === undefined || listId === null)
            throw new globalThis.Error("The parameter 'listId' must be defined.");
        url_ = url_.replace("{listId}", encodeURIComponent("" + listId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetListById(_response);
        });
    }

    protected processGetListById(response: Response): Promise<ListDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ListDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ListDto>(null as any);
    }

    addListItem(listId: string, request: AddListItemRequest): Promise<ListItemDto> {
        let url_ = this.baseUrl + "/api/lists/{listId}/items";
        if (listId === undefined || listId === null)
            throw new globalThis.Error("The parameter 'listId' must be defined.");
        url_ = url_.replace("{listId}", encodeURIComponent("" + listId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAddListItem(_response);
        });
    }

    protected processAddListItem(response: Response): Promise<ListItemDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = ListItemDto.fromJS(resultData201);
            return result201;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ListItemDto>(null as any);
    }

    toggleListItemCompletion(listId: string, itemId: string): Promise<ListItemDto> {
        let url_ = this.baseUrl + "/api/lists/{listId}/items/{itemId}/toggle";
        if (listId === undefined || listId === null)
            throw new globalThis.Error("The parameter 'listId' must be defined.");
        url_ = url_.replace("{listId}", encodeURIComponent("" + listId));
        if (itemId === undefined || itemId === null)
            throw new globalThis.Error("The parameter 'itemId' must be defined.");
        url_ = url_.replace("{itemId}", encodeURIComponent("" + itemId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processToggleListItemCompletion(_response);
        });
    }

    protected processToggleListItemCompletion(response: Response): Promise<ListItemDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ListItemDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ListItemDto>(null as any);
    }

    removeListItem(listId: string, itemId: string): Promise<void> {
        let url_ = this.baseUrl + "/api/lists/{listId}/items/{itemId}";
        if (listId === undefined || listId === null)
            throw new globalThis.Error("The parameter 'listId' must be defined.");
        url_ = url_.replace("{listId}", encodeURIComponent("" + listId));
        if (itemId === undefined || itemId === null)
            throw new globalThis.Error("The parameter 'itemId' must be defined.");
        url_ = url_.replace("{itemId}", encodeURIComponent("" + itemId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRemoveListItem(_response);
        });
    }

    protected processRemoveListItem(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    getWorkspaceLayout(workspaceKey: string): Promise<WorkspaceLayoutDto> {
        let url_ = this.baseUrl + "/api/workspaces/{workspaceKey}/layout";
        if (workspaceKey === undefined || workspaceKey === null)
            throw new globalThis.Error("The parameter 'workspaceKey' must be defined.");
        url_ = url_.replace("{workspaceKey}", encodeURIComponent("" + workspaceKey));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetWorkspaceLayout(_response);
        });
    }

    protected processGetWorkspaceLayout(response: Response): Promise<WorkspaceLayoutDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = WorkspaceLayoutDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WorkspaceLayoutDto>(null as any);
    }

    saveWorkspaceLayout(workspaceKey: string, request: SaveWorkspaceLayoutRequest): Promise<WorkspaceLayoutDto> {
        let url_ = this.baseUrl + "/api/workspaces/{workspaceKey}/layout";
        if (workspaceKey === undefined || workspaceKey === null)
            throw new globalThis.Error("The parameter 'workspaceKey' must be defined.");
        url_ = url_.replace("{workspaceKey}", encodeURIComponent("" + workspaceKey));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSaveWorkspaceLayout(_response);
        });
    }

    protected processSaveWorkspaceLayout(response: Response): Promise<WorkspaceLayoutDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = WorkspaceLayoutDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WorkspaceLayoutDto>(null as any);
    }

    exportCalendar(): Promise<CalendarExportDocument> {
        let url_ = this.baseUrl + "/api/calendar/export";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processExportCalendar(_response);
        });
    }

    protected processExportCalendar(response: Response): Promise<CalendarExportDocument> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CalendarExportDocument.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CalendarExportDocument>(null as any);
    }

    restoreCalendar(document: CalendarExportDocument): Promise<void> {
        let url_ = this.baseUrl + "/api/calendar/restore";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(document);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRestoreCalendar(_response);
        });
    }

    protected processRestoreCalendar(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = HttpValidationProblemDetails.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    getEvents(): Promise<NormalizedEvent[]> {
        let url_ = this.baseUrl + "/api/events";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetEvents(_response);
        });
    }

    protected processGetEvents(response: Response): Promise<NormalizedEvent[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(NormalizedEvent.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<NormalizedEvent[]>(null as any);
    }

    createEvent(request: CreateEventSeriesRequest): Promise<EventSeriesDto> {
        let url_ = this.baseUrl + "/api/events";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateEvent(_response);
        });
    }

    protected processCreateEvent(response: Response): Promise<EventSeriesDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = EventSeriesDto.fromJS(resultData201);
            return result201;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<EventSeriesDto>(null as any);
    }

    getEventById(eventId: string): Promise<EventSeriesDto> {
        let url_ = this.baseUrl + "/api/events/{eventId}";
        if (eventId === undefined || eventId === null)
            throw new globalThis.Error("The parameter 'eventId' must be defined.");
        url_ = url_.replace("{eventId}", encodeURIComponent("" + eventId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetEventById(_response);
        });
    }

    protected processGetEventById(response: Response): Promise<EventSeriesDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = EventSeriesDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<EventSeriesDto>(null as any);
    }

    updateEvent(eventId: string, request: UpdateEventSeriesRequest): Promise<EventSeriesDto> {
        let url_ = this.baseUrl + "/api/events/{eventId}";
        if (eventId === undefined || eventId === null)
            throw new globalThis.Error("The parameter 'eventId' must be defined.");
        url_ = url_.replace("{eventId}", encodeURIComponent("" + eventId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateEvent(_response);
        });
    }

    protected processUpdateEvent(response: Response): Promise<EventSeriesDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = EventSeriesDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<EventSeriesDto>(null as any);
    }

    deleteEvent(eventId: string): Promise<void> {
        let url_ = this.baseUrl + "/api/events/{eventId}";
        if (eventId === undefined || eventId === null)
            throw new globalThis.Error("The parameter 'eventId' must be defined.");
        url_ = url_.replace("{eventId}", encodeURIComponent("" + eventId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteEvent(_response);
        });
    }

    protected processDeleteEvent(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class EventSource implements IEventSource {
    id?: string;
    name?: string;
    type?: EventSourceType;
    enabled?: boolean;
    capability?: EventSourceCapability;
    visibility?: EventSourceVisibility;
    color?: EventSourceColor;
    externalSourceId?: string | undefined;
    isReadOnly?: boolean;
    isWritable?: boolean;

    constructor(data?: IEventSource) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.type = _data["type"];
            this.enabled = _data["enabled"];
            this.capability = _data["capability"];
            this.visibility = _data["visibility"] ? EventSourceVisibility.fromJS(_data["visibility"]) : undefined as any;
            this.color = _data["color"] ? EventSourceColor.fromJS(_data["color"]) : undefined as any;
            this.externalSourceId = _data["externalSourceId"];
            this.isReadOnly = _data["isReadOnly"];
            this.isWritable = _data["isWritable"];
        }
    }

    static fromJS(data: any): EventSource {
        data = typeof data === 'object' ? data : {};
        let result = new EventSource();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["type"] = this.type;
        data["enabled"] = this.enabled;
        data["capability"] = this.capability;
        data["visibility"] = this.visibility ? this.visibility.toJSON() : undefined as any;
        data["color"] = this.color ? this.color.toJSON() : undefined as any;
        data["externalSourceId"] = this.externalSourceId;
        data["isReadOnly"] = this.isReadOnly;
        data["isWritable"] = this.isWritable;
        return data;
    }
}

export interface IEventSource {
    id?: string;
    name?: string;
    type?: EventSourceType;
    enabled?: boolean;
    capability?: EventSourceCapability;
    visibility?: EventSourceVisibility;
    color?: EventSourceColor;
    externalSourceId?: string | undefined;
    isReadOnly?: boolean;
    isWritable?: boolean;
}

export enum EventSourceType {
    Manual = 0,
    GoogleCalendar = 1,
    Birthdays = 2,
    TvSeries = 3,
    SchoolHolidays = 4,
    External = 99,
}

export enum EventSourceCapability {
    ReadOnly = 0,
    Writable = 1,
}

export class EventSourceVisibility implements IEventSourceVisibility {
    visibleByDefault?: boolean;
    groupName?: string | undefined;

    constructor(data?: IEventSourceVisibility) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.visibleByDefault = _data["visibleByDefault"];
            this.groupName = _data["groupName"];
        }
    }

    static fromJS(data: any): EventSourceVisibility {
        data = typeof data === 'object' ? data : {};
        let result = new EventSourceVisibility();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["visibleByDefault"] = this.visibleByDefault;
        data["groupName"] = this.groupName;
        return data;
    }
}

export interface IEventSourceVisibility {
    visibleByDefault?: boolean;
    groupName?: string | undefined;
}

export class EventSourceColor implements IEventSourceColor {
    hex?: string | undefined;

    constructor(data?: IEventSourceColor) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.hex = _data["hex"];
        }
    }

    static fromJS(data: any): EventSourceColor {
        data = typeof data === 'object' ? data : {};
        let result = new EventSourceColor();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["hex"] = this.hex;
        return data;
    }
}

export interface IEventSourceColor {
    hex?: string | undefined;
}

export class AgendaLayerSettingsDto implements IAgendaLayerSettingsDto {
    week?: { [key: string]: boolean; };
    months?: { [key: string]: boolean; };

    constructor(data?: IAgendaLayerSettingsDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (_data["week"]) {
                this.week = {} as any;
                for (let key in _data["week"]) {
                    if (_data["week"].hasOwnProperty(key))
                        (this.week as any)![key] = _data["week"][key];
                }
            }
            if (_data["months"]) {
                this.months = {} as any;
                for (let key in _data["months"]) {
                    if (_data["months"].hasOwnProperty(key))
                        (this.months as any)![key] = _data["months"][key];
                }
            }
        }
    }

    static fromJS(data: any): AgendaLayerSettingsDto {
        data = typeof data === 'object' ? data : {};
        let result = new AgendaLayerSettingsDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (this.week) {
            data["week"] = {};
            for (let key in this.week) {
                if (this.week.hasOwnProperty(key))
                    (data["week"] as any)[key] = (this.week as any)[key];
            }
        }
        if (this.months) {
            data["months"] = {};
            for (let key in this.months) {
                if (this.months.hasOwnProperty(key))
                    (data["months"] as any)[key] = (this.months as any)[key];
            }
        }
        return data;
    }
}

export interface IAgendaLayerSettingsDto {
    week?: { [key: string]: boolean; };
    months?: { [key: string]: boolean; };
}

export class SaveAgendaLayerSettingsRequest implements ISaveAgendaLayerSettingsRequest {
    week?: { [key: string]: boolean; };
    months?: { [key: string]: boolean; };

    constructor(data?: ISaveAgendaLayerSettingsRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (_data["week"]) {
                this.week = {} as any;
                for (let key in _data["week"]) {
                    if (_data["week"].hasOwnProperty(key))
                        (this.week as any)![key] = _data["week"][key];
                }
            }
            if (_data["months"]) {
                this.months = {} as any;
                for (let key in _data["months"]) {
                    if (_data["months"].hasOwnProperty(key))
                        (this.months as any)![key] = _data["months"][key];
                }
            }
        }
    }

    static fromJS(data: any): SaveAgendaLayerSettingsRequest {
        data = typeof data === 'object' ? data : {};
        let result = new SaveAgendaLayerSettingsRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (this.week) {
            data["week"] = {};
            for (let key in this.week) {
                if (this.week.hasOwnProperty(key))
                    (data["week"] as any)[key] = (this.week as any)[key];
            }
        }
        if (this.months) {
            data["months"] = {};
            for (let key in this.months) {
                if (this.months.hasOwnProperty(key))
                    (data["months"] as any)[key] = (this.months as any)[key];
            }
        }
        return data;
    }
}

export interface ISaveAgendaLayerSettingsRequest {
    week?: { [key: string]: boolean; };
    months?: { [key: string]: boolean; };
}

export class ListSummaryDto implements IListSummaryDto {
    id?: string;
    name?: string;
    createdUtc?: Date;
    updatedUtc?: Date;
    householdId?: string;
    itemCount?: number;

    constructor(data?: IListSummaryDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.createdUtc = _data["createdUtc"] ? new Date(_data["createdUtc"].toString()) : undefined as any;
            this.updatedUtc = _data["updatedUtc"] ? new Date(_data["updatedUtc"].toString()) : undefined as any;
            this.householdId = _data["householdId"];
            this.itemCount = _data["itemCount"];
        }
    }

    static fromJS(data: any): ListSummaryDto {
        data = typeof data === 'object' ? data : {};
        let result = new ListSummaryDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["createdUtc"] = this.createdUtc ? this.createdUtc.toISOString() : undefined as any;
        data["updatedUtc"] = this.updatedUtc ? this.updatedUtc.toISOString() : undefined as any;
        data["householdId"] = this.householdId;
        data["itemCount"] = this.itemCount;
        return data;
    }
}

export interface IListSummaryDto {
    id?: string;
    name?: string;
    createdUtc?: Date;
    updatedUtc?: Date;
    householdId?: string;
    itemCount?: number;
}

export class ListDto implements IListDto {
    id?: string;
    name?: string;
    createdUtc?: Date;
    updatedUtc?: Date;
    householdId?: string;
    items?: ListItemDto[];

    constructor(data?: IListDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.createdUtc = _data["createdUtc"] ? new Date(_data["createdUtc"].toString()) : undefined as any;
            this.updatedUtc = _data["updatedUtc"] ? new Date(_data["updatedUtc"].toString()) : undefined as any;
            this.householdId = _data["householdId"];
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(ListItemDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ListDto {
        data = typeof data === 'object' ? data : {};
        let result = new ListDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["createdUtc"] = this.createdUtc ? this.createdUtc.toISOString() : undefined as any;
        data["updatedUtc"] = this.updatedUtc ? this.updatedUtc.toISOString() : undefined as any;
        data["householdId"] = this.householdId;
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IListDto {
    id?: string;
    name?: string;
    createdUtc?: Date;
    updatedUtc?: Date;
    householdId?: string;
    items?: ListItemDto[];
}

export class ListItemDto implements IListItemDto {
    id?: string;
    listId?: string;
    text?: string;
    isCompleted?: boolean;
    createdUtc?: Date;
    updatedUtc?: Date;

    constructor(data?: IListItemDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.listId = _data["listId"];
            this.text = _data["text"];
            this.isCompleted = _data["isCompleted"];
            this.createdUtc = _data["createdUtc"] ? new Date(_data["createdUtc"].toString()) : undefined as any;
            this.updatedUtc = _data["updatedUtc"] ? new Date(_data["updatedUtc"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): ListItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new ListItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["listId"] = this.listId;
        data["text"] = this.text;
        data["isCompleted"] = this.isCompleted;
        data["createdUtc"] = this.createdUtc ? this.createdUtc.toISOString() : undefined as any;
        data["updatedUtc"] = this.updatedUtc ? this.updatedUtc.toISOString() : undefined as any;
        return data;
    }
}

export interface IListItemDto {
    id?: string;
    listId?: string;
    text?: string;
    isCompleted?: boolean;
    createdUtc?: Date;
    updatedUtc?: Date;
}

export class CreateListRequest implements ICreateListRequest {
    name?: string;

    constructor(data?: ICreateListRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): CreateListRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateListRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        return data;
    }
}

export interface ICreateListRequest {
    name?: string;
}

export class AddListItemRequest implements IAddListItemRequest {
    text?: string;

    constructor(data?: IAddListItemRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.text = _data["text"];
        }
    }

    static fromJS(data: any): AddListItemRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AddListItemRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["text"] = this.text;
        return data;
    }
}

export interface IAddListItemRequest {
    text?: string;
}

export class WorkspaceLayoutDto implements IWorkspaceLayoutDto {
    id?: string;
    householdId?: string;
    workspaceKey?: string;
    createdUtc?: Date;
    updatedUtc?: Date;
    placements?: WidgetPlacementDto[];

    constructor(data?: IWorkspaceLayoutDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.householdId = _data["householdId"];
            this.workspaceKey = _data["workspaceKey"];
            this.createdUtc = _data["createdUtc"] ? new Date(_data["createdUtc"].toString()) : undefined as any;
            this.updatedUtc = _data["updatedUtc"] ? new Date(_data["updatedUtc"].toString()) : undefined as any;
            if (Array.isArray(_data["placements"])) {
                this.placements = [] as any;
                for (let item of _data["placements"])
                    this.placements!.push(WidgetPlacementDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): WorkspaceLayoutDto {
        data = typeof data === 'object' ? data : {};
        let result = new WorkspaceLayoutDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["householdId"] = this.householdId;
        data["workspaceKey"] = this.workspaceKey;
        data["createdUtc"] = this.createdUtc ? this.createdUtc.toISOString() : undefined as any;
        data["updatedUtc"] = this.updatedUtc ? this.updatedUtc.toISOString() : undefined as any;
        if (Array.isArray(this.placements)) {
            data["placements"] = [];
            for (let item of this.placements)
                data["placements"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IWorkspaceLayoutDto {
    id?: string;
    householdId?: string;
    workspaceKey?: string;
    createdUtc?: Date;
    updatedUtc?: Date;
    placements?: WidgetPlacementDto[];
}

export class WidgetPlacementDto implements IWidgetPlacementDto {
    id?: string;
    widgetType?: string;
    position?: number;
    size?: string;
    configurationJson?: string;

    constructor(data?: IWidgetPlacementDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.widgetType = _data["widgetType"];
            this.position = _data["position"];
            this.size = _data["size"];
            this.configurationJson = _data["configurationJson"];
        }
    }

    static fromJS(data: any): WidgetPlacementDto {
        data = typeof data === 'object' ? data : {};
        let result = new WidgetPlacementDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["widgetType"] = this.widgetType;
        data["position"] = this.position;
        data["size"] = this.size;
        data["configurationJson"] = this.configurationJson;
        return data;
    }
}

export interface IWidgetPlacementDto {
    id?: string;
    widgetType?: string;
    position?: number;
    size?: string;
    configurationJson?: string;
}

export class SaveWorkspaceLayoutRequest implements ISaveWorkspaceLayoutRequest {
    placements?: SaveWidgetPlacementRequest[];

    constructor(data?: ISaveWorkspaceLayoutRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["placements"])) {
                this.placements = [] as any;
                for (let item of _data["placements"])
                    this.placements!.push(SaveWidgetPlacementRequest.fromJS(item));
            }
        }
    }

    static fromJS(data: any): SaveWorkspaceLayoutRequest {
        data = typeof data === 'object' ? data : {};
        let result = new SaveWorkspaceLayoutRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.placements)) {
            data["placements"] = [];
            for (let item of this.placements)
                data["placements"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface ISaveWorkspaceLayoutRequest {
    placements?: SaveWidgetPlacementRequest[];
}

export class SaveWidgetPlacementRequest implements ISaveWidgetPlacementRequest {
    widgetType?: string;
    position?: number;
    size?: string;
    configurationJson?: string | undefined;

    constructor(data?: ISaveWidgetPlacementRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.widgetType = _data["widgetType"];
            this.position = _data["position"];
            this.size = _data["size"];
            this.configurationJson = _data["configurationJson"];
        }
    }

    static fromJS(data: any): SaveWidgetPlacementRequest {
        data = typeof data === 'object' ? data : {};
        let result = new SaveWidgetPlacementRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["widgetType"] = this.widgetType;
        data["position"] = this.position;
        data["size"] = this.size;
        data["configurationJson"] = this.configurationJson;
        return data;
    }
}

export interface ISaveWidgetPlacementRequest {
    widgetType?: string;
    position?: number;
    size?: string;
    configurationJson?: string | undefined;
}

export class CalendarExportDocument implements ICalendarExportDocument {
    format?: string;
    schemaVersion?: number;
    exportedUtc?: Date;
    household?: CalendarExportHousehold;
    calendar?: CalendarExportPayload;

    constructor(data?: ICalendarExportDocument) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.format = _data["format"];
            this.schemaVersion = _data["schemaVersion"];
            this.exportedUtc = _data["exportedUtc"] ? new Date(_data["exportedUtc"].toString()) : undefined as any;
            this.household = _data["household"] ? CalendarExportHousehold.fromJS(_data["household"]) : undefined as any;
            this.calendar = _data["calendar"] ? CalendarExportPayload.fromJS(_data["calendar"]) : undefined as any;
        }
    }

    static fromJS(data: any): CalendarExportDocument {
        data = typeof data === 'object' ? data : {};
        let result = new CalendarExportDocument();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["format"] = this.format;
        data["schemaVersion"] = this.schemaVersion;
        data["exportedUtc"] = this.exportedUtc ? this.exportedUtc.toISOString() : undefined as any;
        data["household"] = this.household ? this.household.toJSON() : undefined as any;
        data["calendar"] = this.calendar ? this.calendar.toJSON() : undefined as any;
        return data;
    }
}

export interface ICalendarExportDocument {
    format?: string;
    schemaVersion?: number;
    exportedUtc?: Date;
    household?: CalendarExportHousehold;
    calendar?: CalendarExportPayload;
}

export class CalendarExportHousehold implements ICalendarExportHousehold {
    id?: string;
    timeZoneId?: string;

    constructor(data?: ICalendarExportHousehold) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.timeZoneId = _data["timeZoneId"];
        }
    }

    static fromJS(data: any): CalendarExportHousehold {
        data = typeof data === 'object' ? data : {};
        let result = new CalendarExportHousehold();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["timeZoneId"] = this.timeZoneId;
        return data;
    }
}

export interface ICalendarExportHousehold {
    id?: string;
    timeZoneId?: string;
}

export class CalendarExportPayload implements ICalendarExportPayload {
    version?: number;
    eventSources?: CalendarExportEventSource[];
    eventSeries?: CalendarExportEventSeries[];
    exceptions?: CalendarExportEventException[];

    constructor(data?: ICalendarExportPayload) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.version = _data["version"];
            if (Array.isArray(_data["eventSources"])) {
                this.eventSources = [] as any;
                for (let item of _data["eventSources"])
                    this.eventSources!.push(CalendarExportEventSource.fromJS(item));
            }
            if (Array.isArray(_data["eventSeries"])) {
                this.eventSeries = [] as any;
                for (let item of _data["eventSeries"])
                    this.eventSeries!.push(CalendarExportEventSeries.fromJS(item));
            }
            if (Array.isArray(_data["exceptions"])) {
                this.exceptions = [] as any;
                for (let item of _data["exceptions"])
                    this.exceptions!.push(CalendarExportEventException.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CalendarExportPayload {
        data = typeof data === 'object' ? data : {};
        let result = new CalendarExportPayload();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["version"] = this.version;
        if (Array.isArray(this.eventSources)) {
            data["eventSources"] = [];
            for (let item of this.eventSources)
                data["eventSources"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.eventSeries)) {
            data["eventSeries"] = [];
            for (let item of this.eventSeries)
                data["eventSeries"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.exceptions)) {
            data["exceptions"] = [];
            for (let item of this.exceptions)
                data["exceptions"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface ICalendarExportPayload {
    version?: number;
    eventSources?: CalendarExportEventSource[];
    eventSeries?: CalendarExportEventSeries[];
    exceptions?: CalendarExportEventException[];
}

export class CalendarExportEventSource implements ICalendarExportEventSource {
    id?: string;
    name?: string;
    sourceType?: string;
    isWritable?: boolean;
    createdUtc?: Date;
    updatedUtc?: Date;

    constructor(data?: ICalendarExportEventSource) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.sourceType = _data["sourceType"];
            this.isWritable = _data["isWritable"];
            this.createdUtc = _data["createdUtc"] ? new Date(_data["createdUtc"].toString()) : undefined as any;
            this.updatedUtc = _data["updatedUtc"] ? new Date(_data["updatedUtc"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): CalendarExportEventSource {
        data = typeof data === 'object' ? data : {};
        let result = new CalendarExportEventSource();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["sourceType"] = this.sourceType;
        data["isWritable"] = this.isWritable;
        data["createdUtc"] = this.createdUtc ? this.createdUtc.toISOString() : undefined as any;
        data["updatedUtc"] = this.updatedUtc ? this.updatedUtc.toISOString() : undefined as any;
        return data;
    }
}

export interface ICalendarExportEventSource {
    id?: string;
    name?: string;
    sourceType?: string;
    isWritable?: boolean;
    createdUtc?: Date;
    updatedUtc?: Date;
}

export class CalendarExportEventSeries implements ICalendarExportEventSeries {
    id?: string;
    eventSourceId?: string;
    title?: string;
    description?: string | undefined;
    isAllDay?: boolean;
    startDate?: Date;
    startTime?: string | undefined;
    endDate?: Date;
    endTime?: string | undefined;
    recurrence?: CalendarExportRecurrence | undefined;
    createdUtc?: Date;
    updatedUtc?: Date;

    constructor(data?: ICalendarExportEventSeries) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.eventSourceId = _data["eventSourceId"];
            this.title = _data["title"];
            this.description = _data["description"];
            this.isAllDay = _data["isAllDay"];
            this.startDate = _data["startDate"] ? new Date(_data["startDate"].toString()) : undefined as any;
            this.startTime = _data["startTime"];
            this.endDate = _data["endDate"] ? new Date(_data["endDate"].toString()) : undefined as any;
            this.endTime = _data["endTime"];
            this.recurrence = _data["recurrence"] ? CalendarExportRecurrence.fromJS(_data["recurrence"]) : undefined as any;
            this.createdUtc = _data["createdUtc"] ? new Date(_data["createdUtc"].toString()) : undefined as any;
            this.updatedUtc = _data["updatedUtc"] ? new Date(_data["updatedUtc"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): CalendarExportEventSeries {
        data = typeof data === 'object' ? data : {};
        let result = new CalendarExportEventSeries();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["eventSourceId"] = this.eventSourceId;
        data["title"] = this.title;
        data["description"] = this.description;
        data["isAllDay"] = this.isAllDay;
        data["startDate"] = this.startDate ? formatDate(this.startDate) : undefined as any;
        data["startTime"] = this.startTime;
        data["endDate"] = this.endDate ? formatDate(this.endDate) : undefined as any;
        data["endTime"] = this.endTime;
        data["recurrence"] = this.recurrence ? this.recurrence.toJSON() : undefined as any;
        data["createdUtc"] = this.createdUtc ? this.createdUtc.toISOString() : undefined as any;
        data["updatedUtc"] = this.updatedUtc ? this.updatedUtc.toISOString() : undefined as any;
        return data;
    }
}

export interface ICalendarExportEventSeries {
    id?: string;
    eventSourceId?: string;
    title?: string;
    description?: string | undefined;
    isAllDay?: boolean;
    startDate?: Date;
    startTime?: string | undefined;
    endDate?: Date;
    endTime?: string | undefined;
    recurrence?: CalendarExportRecurrence | undefined;
    createdUtc?: Date;
    updatedUtc?: Date;
}

export class CalendarExportRecurrence implements ICalendarExportRecurrence {
    ruleType?: string;
    value?: string;

    constructor(data?: ICalendarExportRecurrence) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.ruleType = _data["ruleType"];
            this.value = _data["value"];
        }
    }

    static fromJS(data: any): CalendarExportRecurrence {
        data = typeof data === 'object' ? data : {};
        let result = new CalendarExportRecurrence();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["ruleType"] = this.ruleType;
        data["value"] = this.value;
        return data;
    }
}

export interface ICalendarExportRecurrence {
    ruleType?: string;
    value?: string;
}

export class CalendarExportEventException implements ICalendarExportEventException {
    id?: string;
    eventSeriesId?: string;
    exceptionType?: string;

    constructor(data?: ICalendarExportEventException) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.eventSeriesId = _data["eventSeriesId"];
            this.exceptionType = _data["exceptionType"];
        }
    }

    static fromJS(data: any): CalendarExportEventException {
        data = typeof data === 'object' ? data : {};
        let result = new CalendarExportEventException();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["eventSeriesId"] = this.eventSeriesId;
        data["exceptionType"] = this.exceptionType;
        return data;
    }
}

export interface ICalendarExportEventException {
    id?: string;
    eventSeriesId?: string;
    exceptionType?: string;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export class HttpValidationProblemDetails extends ProblemDetails implements IHttpValidationProblemDetails {
    errors?: { [key: string]: string[]; };

    [key: string]: any;

    constructor(data?: IHttpValidationProblemDetails) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            if (_data["errors"]) {
                this.errors = {} as any;
                for (let key in _data["errors"]) {
                    if (_data["errors"].hasOwnProperty(key))
                        (this.errors as any)![key] = _data["errors"][key] !== undefined ? _data["errors"][key] : [];
                }
            }
        }
    }

    static override fromJS(data: any): HttpValidationProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new HttpValidationProblemDetails();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        if (this.errors) {
            data["errors"] = {};
            for (let key in this.errors) {
                if (this.errors.hasOwnProperty(key))
                    (data["errors"] as any)[key] = (this.errors as any)[key];
            }
        }
        super.toJSON(data);
        return data;
    }
}

export interface IHttpValidationProblemDetails extends IProblemDetails {
    errors?: { [key: string]: string[]; };

    [key: string]: any;
}

export class NormalizedEvent implements INormalizedEvent {
    id?: string;
    sourceId?: string;
    title?: string;
    startsAt?: Date;
    endsAt?: Date | undefined;
    allDay?: boolean;
    editable?: boolean;
    externalEventId?: string | undefined;
    description?: string | undefined;
    location?: string | undefined;

    constructor(data?: INormalizedEvent) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.sourceId = _data["sourceId"];
            this.title = _data["title"];
            this.startsAt = _data["startsAt"] ? new Date(_data["startsAt"].toString()) : undefined as any;
            this.endsAt = _data["endsAt"] ? new Date(_data["endsAt"].toString()) : undefined as any;
            this.allDay = _data["allDay"];
            this.editable = _data["editable"];
            this.externalEventId = _data["externalEventId"];
            this.description = _data["description"];
            this.location = _data["location"];
        }
    }

    static fromJS(data: any): NormalizedEvent {
        data = typeof data === 'object' ? data : {};
        let result = new NormalizedEvent();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["sourceId"] = this.sourceId;
        data["title"] = this.title;
        data["startsAt"] = this.startsAt ? this.startsAt.toISOString() : undefined as any;
        data["endsAt"] = this.endsAt ? this.endsAt.toISOString() : undefined as any;
        data["allDay"] = this.allDay;
        data["editable"] = this.editable;
        data["externalEventId"] = this.externalEventId;
        data["description"] = this.description;
        data["location"] = this.location;
        return data;
    }
}

export interface INormalizedEvent {
    id?: string;
    sourceId?: string;
    title?: string;
    startsAt?: Date;
    endsAt?: Date | undefined;
    allDay?: boolean;
    editable?: boolean;
    externalEventId?: string | undefined;
    description?: string | undefined;
    location?: string | undefined;
}

export class EventSeriesDto implements IEventSeriesDto {
    id?: string;
    eventSourceId?: string;
    title?: string;
    description?: string | undefined;
    startUtc?: Date;
    endUtc?: Date | undefined;
    isAllDay?: boolean;
    createdUtc?: Date;
    updatedUtc?: Date;

    constructor(data?: IEventSeriesDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.eventSourceId = _data["eventSourceId"];
            this.title = _data["title"];
            this.description = _data["description"];
            this.startUtc = _data["startUtc"] ? new Date(_data["startUtc"].toString()) : undefined as any;
            this.endUtc = _data["endUtc"] ? new Date(_data["endUtc"].toString()) : undefined as any;
            this.isAllDay = _data["isAllDay"];
            this.createdUtc = _data["createdUtc"] ? new Date(_data["createdUtc"].toString()) : undefined as any;
            this.updatedUtc = _data["updatedUtc"] ? new Date(_data["updatedUtc"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): EventSeriesDto {
        data = typeof data === 'object' ? data : {};
        let result = new EventSeriesDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["eventSourceId"] = this.eventSourceId;
        data["title"] = this.title;
        data["description"] = this.description;
        data["startUtc"] = this.startUtc ? this.startUtc.toISOString() : undefined as any;
        data["endUtc"] = this.endUtc ? this.endUtc.toISOString() : undefined as any;
        data["isAllDay"] = this.isAllDay;
        data["createdUtc"] = this.createdUtc ? this.createdUtc.toISOString() : undefined as any;
        data["updatedUtc"] = this.updatedUtc ? this.updatedUtc.toISOString() : undefined as any;
        return data;
    }
}

export interface IEventSeriesDto {
    id?: string;
    eventSourceId?: string;
    title?: string;
    description?: string | undefined;
    startUtc?: Date;
    endUtc?: Date | undefined;
    isAllDay?: boolean;
    createdUtc?: Date;
    updatedUtc?: Date;
}

export class CreateEventSeriesRequest implements ICreateEventSeriesRequest {
    title?: string;
    description?: string | undefined;
    startUtc?: Date;
    endUtc?: Date | undefined;
    isAllDay?: boolean;

    constructor(data?: ICreateEventSeriesRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["title"];
            this.description = _data["description"];
            this.startUtc = _data["startUtc"] ? new Date(_data["startUtc"].toString()) : undefined as any;
            this.endUtc = _data["endUtc"] ? new Date(_data["endUtc"].toString()) : undefined as any;
            this.isAllDay = _data["isAllDay"];
        }
    }

    static fromJS(data: any): CreateEventSeriesRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateEventSeriesRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        data["description"] = this.description;
        data["startUtc"] = this.startUtc ? this.startUtc.toISOString() : undefined as any;
        data["endUtc"] = this.endUtc ? this.endUtc.toISOString() : undefined as any;
        data["isAllDay"] = this.isAllDay;
        return data;
    }
}

export interface ICreateEventSeriesRequest {
    title?: string;
    description?: string | undefined;
    startUtc?: Date;
    endUtc?: Date | undefined;
    isAllDay?: boolean;
}

export class UpdateEventSeriesRequest implements IUpdateEventSeriesRequest {
    title?: string;
    description?: string | undefined;
    startUtc?: Date;
    endUtc?: Date | undefined;
    isAllDay?: boolean;

    constructor(data?: IUpdateEventSeriesRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["title"];
            this.description = _data["description"];
            this.startUtc = _data["startUtc"] ? new Date(_data["startUtc"].toString()) : undefined as any;
            this.endUtc = _data["endUtc"] ? new Date(_data["endUtc"].toString()) : undefined as any;
            this.isAllDay = _data["isAllDay"];
        }
    }

    static fromJS(data: any): UpdateEventSeriesRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateEventSeriesRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        data["description"] = this.description;
        data["startUtc"] = this.startUtc ? this.startUtc.toISOString() : undefined as any;
        data["endUtc"] = this.endUtc ? this.endUtc.toISOString() : undefined as any;
        data["isAllDay"] = this.isAllDay;
        return data;
    }
}

export interface IUpdateEventSeriesRequest {
    title?: string;
    description?: string | undefined;
    startUtc?: Date;
    endUtc?: Date | undefined;
    isAllDay?: boolean;
}

function formatDate(d: Date) {
    return d.getFullYear() + '-' + 
        (d.getMonth() < 9 ? ('0' + (d.getMonth()+1)) : (d.getMonth()+1)) + '-' +
        (d.getDate() < 10 ? ('0' + d.getDate()) : d.getDate());
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}