using HomeOps.Api.Data;
using HomeOps.Api.Households;
using Microsoft.EntityFrameworkCore;

namespace HomeOps.Api.FloorPlans;

public static class ClimateProviderMappingEndpoints
{
    public static IEndpointRouteBuilder MapClimateProviderMappingEndpoints(this IEndpointRouteBuilder app)
    {
        var providers = app.MapGroup("/api/climate-providers").WithTags("Climate Providers");
        providers.MapGet("/", ListProviders).WithName("GetClimateProviders").Produces<IReadOnlyCollection<ClimateProviderDto>>();
        providers.MapGet("/{providerId:guid}", GetProvider).WithName("GetClimateProvider").Produces<ClimateProviderDto>().Produces(404);
        providers.MapPost("/", CreateProvider).WithName("CreateClimateProvider").Produces<ClimateProviderDto>(201).Produces(400);
        providers.MapPut("/{providerId:guid}", UpdateProvider).WithName("UpdateClimateProvider").Produces<ClimateProviderDto>().Produces(400).Produces(404);
        providers.MapPost("/{providerId:guid}/archive", ArchiveProvider).WithName("ArchiveClimateProvider").Produces(204).Produces(404);
        providers.MapPost("/{providerId:guid}/restore", RestoreProvider).WithName("RestoreClimateProvider").Produces<ClimateProviderDto>().Produces(400).Produces(404);
        providers.MapDelete("/{providerId:guid}", DeleteProvider).WithName("DeleteClimateProvider").Produces(204).Produces(400).Produces(404);

        var rooms = app.MapGroup("/api/rooms").WithTags("Room Climate Mappings");
        rooms.MapGet("/{roomId:guid}/climate-mappings", ListRoomMappings).WithName("GetRoomClimateMappings").Produces<IReadOnlyCollection<ClimateMappingDto>>().Produces(404);
        rooms.MapPost("/{roomId:guid}/climate-mappings", CreateMapping).WithName("CreateRoomClimateMapping").Produces<ClimateMappingDto>(201).Produces(400).Produces(404);
        rooms.MapPost("/{roomId:guid}/climate-mappings/{role}/reorder", ReorderMappings).WithName("ReorderRoomClimateMappings").Produces(204).Produces(400).Produces(404);
        rooms.MapGet("/{roomId:guid}/climate-capabilities", GetCapabilities).WithName("GetRoomClimateCapabilities").Produces<ClimateCapabilitySummaryDto>().Produces(404);
        var mappings = app.MapGroup("/api/climate-mappings").WithTags("Room Climate Mappings");
        mappings.MapGet("/{mappingId:guid}", GetMapping).WithName("GetClimateMapping").Produces<ClimateMappingDto>().Produces(404);
        mappings.MapPut("/{mappingId:guid}", UpdateMapping).WithName("UpdateClimateMapping").Produces<ClimateMappingDto>().Produces(400).Produces(404);
        mappings.MapPost("/{mappingId:guid}/archive", ArchiveMapping).WithName("ArchiveClimateMapping").Produces(204).Produces(404);
        mappings.MapPost("/{mappingId:guid}/restore", RestoreMapping).WithName("RestoreClimateMapping").Produces<ClimateMappingDto>().Produces(400).Produces(404);
        mappings.MapDelete("/{mappingId:guid}", DeleteMapping).WithName("DeleteClimateMapping").Produces(204).Produces(404);
        return app;
    }

    private static async Task<IResult> ListProviders(bool? includeArchived, HomeOpsDbContext db, CancellationToken ct)
    { var q = db.ClimateProviders.AsNoTracking().Where(p => p.HouseholdId == SeedHousehold.Id); if (includeArchived != true) q = q.Where(p => !p.IsArchived); return Results.Ok((await q.OrderBy(p => p.DisplayName).ToListAsync(ct)).Select(ToProviderDto)); }
    private static async Task<IResult> GetProvider(Guid providerId, HomeOpsDbContext db, CancellationToken ct) => await db.ClimateProviders.AsNoTracking().FirstOrDefaultAsync(p => p.Id == providerId && p.HouseholdId == SeedHousehold.Id, ct) is { } p ? Results.Ok(ToProviderDto(p)) : Results.NotFound();
    private static async Task<IResult> CreateProvider(CreateClimateProviderRequest req, HomeOpsDbContext db, CancellationToken ct)
    { var name = Clean(req.DisplayName,160); if (name is null) return Bad("displayName","Provider display name is required."); if (!Enum.IsDefined(req.ProviderType)) return Bad("providerType","Provider type is not supported."); if (await db.ClimateProviders.AnyAsync(p=>p.HouseholdId==SeedHousehold.Id&&!p.IsArchived&&p.DisplayName==name,ct)) return Bad("displayName","An active provider with this display name already exists."); var now=DateTimeOffset.UtcNow; var p=new ClimateProvider{Id=Guid.NewGuid(),HouseholdId=SeedHousehold.Id,DisplayName=name,ProviderType=req.ProviderType,ExternalInstanceReference=Clean(req.ExternalInstanceReference,240),DiagnosticMetadata=Clean(req.DiagnosticMetadata,2000),CreatedUtc=now,UpdatedUtc=now}; db.ClimateProviders.Add(p); await db.SaveChangesAsync(ct); return Results.Created($"/api/climate-providers/{p.Id}", ToProviderDto(p)); }
    private static async Task<IResult> UpdateProvider(Guid providerId, UpdateClimateProviderRequest req, HomeOpsDbContext db, CancellationToken ct)
    { var p=await db.ClimateProviders.FirstOrDefaultAsync(x=>x.Id==providerId&&x.HouseholdId==SeedHousehold.Id,ct); if(p is null) return Results.NotFound(); var name=Clean(req.DisplayName,160); if(name is null) return Bad("displayName","Provider display name is required."); if(!p.IsArchived && await db.ClimateProviders.AnyAsync(x=>x.HouseholdId==SeedHousehold.Id&&!x.IsArchived&&x.Id!=providerId&&x.DisplayName==name,ct)) return Bad("displayName","An active provider with this display name already exists."); p.DisplayName=name; p.IsEnabled=req.IsEnabled??p.IsEnabled; p.ExternalInstanceReference=Clean(req.ExternalInstanceReference,240); p.DiagnosticMetadata=Clean(req.DiagnosticMetadata,2000); p.UpdatedUtc=DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); return Results.Ok(ToProviderDto(p)); }
    private static async Task<IResult> ArchiveProvider(Guid providerId, HomeOpsDbContext db, CancellationToken ct){ var p=await db.ClimateProviders.FirstOrDefaultAsync(x=>x.Id==providerId&&x.HouseholdId==SeedHousehold.Id,ct); if(p is null)return Results.NotFound(); p.IsArchived=true;p.IsEnabled=false;p.ArchivedUtc=DateTimeOffset.UtcNow;p.UpdatedUtc=p.ArchivedUtc.Value; await db.SaveChangesAsync(ct); return Results.NoContent();}
    private static async Task<IResult> RestoreProvider(Guid providerId, HomeOpsDbContext db, CancellationToken ct){ var p=await db.ClimateProviders.FirstOrDefaultAsync(x=>x.Id==providerId&&x.HouseholdId==SeedHousehold.Id,ct); if(p is null)return Results.NotFound(); if(await db.ClimateProviders.AnyAsync(x=>x.HouseholdId==SeedHousehold.Id&&!x.IsArchived&&x.Id!=providerId&&x.DisplayName==p.DisplayName,ct)) return Bad("displayName","Rename the conflicting active provider before restoring this provider."); p.IsArchived=false;p.IsEnabled=true;p.ArchivedUtc=null;p.UpdatedUtc=DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); return Results.Ok(ToProviderDto(p));}
    private static async Task<IResult> DeleteProvider(Guid providerId, HomeOpsDbContext db, CancellationToken ct){ var p=await db.ClimateProviders.FirstOrDefaultAsync(x=>x.Id==providerId&&x.HouseholdId==SeedHousehold.Id,ct); if(p is null)return Results.NotFound(); if(await db.RoomClimateSourceMappings.AnyAsync(m=>m.ProviderId==providerId&&m.HouseholdId==SeedHousehold.Id,ct)) return Bad("providerId","Provider cannot be deleted while climate mappings reference it."); db.ClimateProviders.Remove(p); await db.SaveChangesAsync(ct); return Results.NoContent();}

    private static async Task<IResult> ListRoomMappings(Guid roomId, bool? includeArchived, HomeOpsDbContext db, CancellationToken ct){ if(!await db.Rooms.AnyAsync(r=>r.Id==roomId&&r.HouseholdId==SeedHousehold.Id,ct)) return Results.NotFound(); var q=db.RoomClimateSourceMappings.AsNoTracking().Where(m=>m.RoomId==roomId&&m.HouseholdId==SeedHousehold.Id); if(includeArchived!=true) q=q.Where(m=>!m.IsArchived); var list=await q.OrderBy(m=>m.SourceRole).ThenBy(m=>m.Priority).ToListAsync(ct); return Results.Ok(await ToMappingDtos(db,list,ct)); }
    private static async Task<IResult> GetMapping(Guid mappingId, HomeOpsDbContext db, CancellationToken ct){ var m=await db.RoomClimateSourceMappings.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==mappingId&&x.HouseholdId==SeedHousehold.Id,ct); return m is null?Results.NotFound():Results.Ok((await ToMappingDtos(db,[m],ct)).Single());}
    private static async Task<IResult> CreateMapping(Guid roomId, CreateClimateMappingRequest req, HomeOpsDbContext db, CancellationToken ct)
    { var v=await ValidateCreate(db,roomId,req.ProviderId,req.SourceRole,req.Source,ct); if(v is not null)return v; if(await db.RoomClimateSourceMappings.AnyAsync(m=>m.RoomId==roomId&&m.SourceRole==req.SourceRole&&m.ProviderId==req.ProviderId&&m.ExternalSourceId==req.Source.ExternalSourceId.Trim()&&!m.IsArchived,ct)) return Bad("source","A mapping for this Room, role, provider, and external source already exists."); var priority=req.Priority ?? ((await db.RoomClimateSourceMappings.Where(m=>m.RoomId==roomId&&m.SourceRole==req.SourceRole&&!m.IsArchived).MaxAsync(m=>(int?)m.Priority,ct))??-1)+1; if(priority<0) return Bad("priority","Priority must be zero or greater; lower numbers are preferred."); if(await db.RoomClimateSourceMappings.AnyAsync(m=>m.RoomId==roomId&&m.SourceRole==req.SourceRole&&!m.IsArchived&&m.Priority==priority,ct)) return Bad("priority","Priority must be unique within a Room and source role."); var now=DateTimeOffset.UtcNow; var m=new RoomClimateSourceMapping{Id=Guid.NewGuid(),HouseholdId=SeedHousehold.Id,RoomId=roomId,ProviderId=req.ProviderId,SourceRole=req.SourceRole,ExternalSourceId=req.Source.ExternalSourceId.Trim(),ExternalDisplayName=Clean(req.Source.ExternalDisplayName,240),ExternalSourceKind=Clean(req.Source.ExternalSourceKind,80),ExternalAreaId=Clean(req.Source.ExternalAreaId,160),ExternalAreaName=Clean(req.Source.ExternalAreaName,160),ExternalDeviceId=Clean(req.Source.ExternalDeviceId,160),ExternalDeviceName=Clean(req.Source.ExternalDeviceName,160),Priority=priority,IsEnabled=req.IsEnabled,Health=MappingHealth.Unverified,CreatedUtc=now,UpdatedUtc=now}; db.RoomClimateSourceMappings.Add(m); await db.SaveChangesAsync(ct); return Results.Created($"/api/climate-mappings/{m.Id}",(await ToMappingDtos(db,[m],ct)).Single()); }
    private static async Task<IResult> UpdateMapping(Guid mappingId, UpdateClimateMappingRequest req, HomeOpsDbContext db, CancellationToken ct){ var m=await db.RoomClimateSourceMappings.FirstOrDefaultAsync(x=>x.Id==mappingId&&x.HouseholdId==SeedHousehold.Id,ct); if(m is null)return Results.NotFound(); if(req.Source is not null){ if(ValidateSource(req.Source) is { } bad)return bad; var newId=req.Source.ExternalSourceId.Trim(); if(newId!=m.ExternalSourceId){ if(await db.RoomClimateSourceMappings.AnyAsync(x=>x.RoomId==m.RoomId&&x.SourceRole==m.SourceRole&&x.ProviderId==m.ProviderId&&x.ExternalSourceId==newId&&!x.IsArchived&&x.Id!=m.Id,ct)) return Bad("source","A mapping for this Room, role, provider, and external source already exists."); m.Health=MappingHealth.NeedsReview; } m.ExternalSourceId=newId; m.ExternalDisplayName=Clean(req.Source.ExternalDisplayName,240); m.ExternalSourceKind=Clean(req.Source.ExternalSourceKind,80); m.ExternalAreaId=Clean(req.Source.ExternalAreaId,160); m.ExternalAreaName=Clean(req.Source.ExternalAreaName,160); m.ExternalDeviceId=Clean(req.Source.ExternalDeviceId,160); m.ExternalDeviceName=Clean(req.Source.ExternalDeviceName,160);} if(req.Priority is not null){ if(req.Priority<0)return Bad("priority","Priority must be zero or greater."); if(await db.RoomClimateSourceMappings.AnyAsync(x=>x.RoomId==m.RoomId&&x.SourceRole==m.SourceRole&&!x.IsArchived&&x.Priority==req.Priority&&x.Id!=m.Id,ct)) return Bad("priority","Priority must be unique within a Room and source role."); m.Priority=req.Priority.Value;} m.IsEnabled=req.IsEnabled??m.IsEnabled; m.DiagnosticSummary=Clean(req.DiagnosticSummary,500); m.UpdatedUtc=DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); return Results.Ok((await ToMappingDtos(db,[m],ct)).Single());}
    private static async Task<IResult> ReorderMappings(Guid roomId, string role, ReorderClimateMappingsRequest req, HomeOpsDbContext db, CancellationToken ct){ if(!Enum.TryParse<ClimateSourceRole>(role,true,out var parsed)) return Bad("role","Unsupported source role."); var items=await db.RoomClimateSourceMappings.Where(m=>m.RoomId==roomId&&m.HouseholdId==SeedHousehold.Id&&m.SourceRole==parsed&&!m.IsArchived).ToListAsync(ct); if(items.Count==0 && !await db.Rooms.AnyAsync(r=>r.Id==roomId&&r.HouseholdId==SeedHousehold.Id,ct)) return Results.NotFound(); if(req.MappingIds.Count!=items.Count||req.MappingIds.Distinct().Count()!=req.MappingIds.Count||!req.MappingIds.ToHashSet().SetEquals(items.Select(i=>i.Id))) return Bad("mappingIds","Reorder ids must exactly match active mappings for the Room and role."); var order=req.MappingIds.Select((id,i)=>(id,i)).ToDictionary(x=>x.id,x=>x.i); foreach(var item in items){item.Priority=order[item.Id];item.UpdatedUtc=DateTimeOffset.UtcNow;} await db.SaveChangesAsync(ct); return Results.NoContent();}
    private static async Task<IResult> ArchiveMapping(Guid mappingId, HomeOpsDbContext db, CancellationToken ct){var m=await db.RoomClimateSourceMappings.FirstOrDefaultAsync(x=>x.Id==mappingId&&x.HouseholdId==SeedHousehold.Id,ct); if(m is null)return Results.NotFound(); m.IsArchived=true;m.IsEnabled=false;m.ArchivedUtc=DateTimeOffset.UtcNow;m.UpdatedUtc=m.ArchivedUtc.Value; await db.SaveChangesAsync(ct); return Results.NoContent();}
    private static async Task<IResult> RestoreMapping(Guid mappingId, HomeOpsDbContext db, CancellationToken ct){var m=await db.RoomClimateSourceMappings.FirstOrDefaultAsync(x=>x.Id==mappingId&&x.HouseholdId==SeedHousehold.Id,ct); if(m is null)return Results.NotFound(); var v=await ValidateCreate(db,m.RoomId,m.ProviderId,m.SourceRole,new ExternalSourceReferenceDto(m.ExternalSourceId),ct); if(v is not null)return v; if(await db.RoomClimateSourceMappings.AnyAsync(x=>x.Id!=m.Id&&x.RoomId==m.RoomId&&x.SourceRole==m.SourceRole&&x.ProviderId==m.ProviderId&&x.ExternalSourceId==m.ExternalSourceId&&!x.IsArchived,ct)) return Bad("source","A conflicting active mapping exists."); if(await db.RoomClimateSourceMappings.AnyAsync(x=>x.Id!=m.Id&&x.RoomId==m.RoomId&&x.SourceRole==m.SourceRole&&x.Priority==m.Priority&&!x.IsArchived,ct)) m.Priority=((await db.RoomClimateSourceMappings.Where(x=>x.RoomId==m.RoomId&&x.SourceRole==m.SourceRole&&!x.IsArchived).MaxAsync(x=>(int?)x.Priority,ct))??-1)+1; m.IsArchived=false;m.IsEnabled=true;m.ArchivedUtc=null;m.Health=MappingHealth.NeedsReview;m.UpdatedUtc=DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); return Results.Ok((await ToMappingDtos(db,[m],ct)).Single());}
    private static async Task<IResult> DeleteMapping(Guid mappingId, HomeOpsDbContext db, CancellationToken ct){var m=await db.RoomClimateSourceMappings.FirstOrDefaultAsync(x=>x.Id==mappingId&&x.HouseholdId==SeedHousehold.Id,ct); if(m is null)return Results.NotFound(); db.RoomClimateSourceMappings.Remove(m); await db.SaveChangesAsync(ct); return Results.NoContent();}

    private static async Task<IResult> GetCapabilities(Guid roomId, HomeOpsDbContext db, CancellationToken ct){ var room=await db.Rooms.AsNoTracking().FirstOrDefaultAsync(r=>r.Id==roomId&&r.HouseholdId==SeedHousehold.Id,ct); if(room is null)return Results.NotFound(); var config=await db.RoomClimateConfigurations.AsNoTracking().FirstOrDefaultAsync(c=>c.RoomId==roomId&&c.HouseholdId==SeedHousehold.Id,ct); var required=config is null?[]:FloorPlanEndpoints.DeriveRequiredSourceRoles(config); var roles=Enum.GetValues<ClimateSourceRole>().Select(role=>Summary(role,required.Contains(role),db,roomId)).ToList(); return Results.Ok(new ClimateCapabilitySummaryDto(roomId,config is not null,config?.IsClimateEnabled??false,roles)); }
    private static ClimateCapabilityRoleSummaryDto Summary(ClimateSourceRole role,bool required,HomeOpsDbContext db,Guid roomId){ var all=db.RoomClimateSourceMappings.Include(m=>m.Provider).Where(m=>m.RoomId==roomId&&m.SourceRole==role&&!m.IsArchived).ToList(); var active=all.Where(m=>m.IsEnabled&&m.Provider is {IsEnabled:true,IsArchived:false}&&m.Health is not MappingHealth.Missing and not MappingHealth.Unavailable).ToList(); var status=!required?"NotRequired":active.Count==0?"RequiredUnmapped":active.Any(m=>m.Health==MappingHealth.Healthy)?"Healthy":active.Any(m=>m.Health==MappingHealth.Degraded)?"Degraded":active.Any(m=>m.Health==MappingHealth.Unverified)?"Unverified":"UnavailableOrMissing"; var shared=active.Any(m=>IsHeatingRole(m.SourceRole)&&db.RoomClimateSourceMappings.Any(o=>o.Id!=m.Id&&o.ProviderId==m.ProviderId&&o.ExternalSourceId==m.ExternalSourceId&&!o.IsArchived)); return new(role,required,status,active.Count,all.Count,active.Any(m=>m.Health==MappingHealth.Healthy),active.Any(m=>m.Health==MappingHealth.Degraded),all.Any(m=>m.Health is MappingHealth.Unavailable or MappingHealth.Missing),shared,active.Select(m=>m.Id).ToList()); }

    private static async Task<IResult?> ValidateCreate(HomeOpsDbContext db, Guid roomId, Guid providerId, ClimateSourceRole role, ExternalSourceReferenceDto src, CancellationToken ct){ var room=await db.Rooms.AsNoTracking().FirstOrDefaultAsync(r=>r.Id==roomId&&r.HouseholdId==SeedHousehold.Id,ct); if(room is null)return Results.NotFound(); if(room.IsArchived||!room.IsEnabled)return Bad("roomId","Climate mappings require an active Room."); var config=await db.RoomClimateConfigurations.AsNoTracking().FirstOrDefaultAsync(c=>c.RoomId==roomId&&c.HouseholdId==SeedHousehold.Id,ct); if(config is null)return Bad("roomId","Room requires climate configuration before mappings can be created."); if(!config.IsClimateEnabled)return Bad("roomId","Climate mappings require an enabled climate configuration."); var provider=await db.ClimateProviders.AsNoTracking().FirstOrDefaultAsync(p=>p.Id==providerId&&p.HouseholdId==SeedHousehold.Id,ct); if(provider is null)return Bad("providerId","Provider must exist in this household."); if(provider.IsArchived||!provider.IsEnabled)return Bad("providerId","Provider must be active."); if(!Enum.IsDefined(role))return Bad("sourceRole","Unsupported source role."); if(!IsRoleAllowed(role,config))return Bad("sourceRole","Source role is not compatible with this Room climate configuration."); return ValidateSource(src); }
    private static bool IsRoleAllowed(ClimateSourceRole role, RoomClimateConfiguration c)=> role switch{ ClimateSourceRole.ComfortTemperature=>c.MinimumPreferredTemperatureCelsius is not null&&c.MaximumPreferredTemperatureCelsius is not null, ClimateSourceRole.Humidity=>c.MinimumPreferredRelativeHumidity is not null&&c.MaximumPreferredRelativeHumidity is not null, ClimateSourceRole.HeatingStatus or ClimateSourceRole.HeatingTargetTemperature=>c.HeatingPolicyIntent is HeatingPolicyIntent.ReadOnlyStatus or HeatingPolicyIntent.BoundedControl, ClimateSourceRole.HeatingControl=>c.HeatingPolicyIntent==HeatingPolicyIntent.BoundedControl, ClimateSourceRole.HeatingControlTemperature=>c.HeatingPolicyIntent is HeatingPolicyIntent.ReadOnlyStatus or HeatingPolicyIntent.BoundedControl, _=>false};
    private static IResult? ValidateSource(ExternalSourceReferenceDto src){ if(string.IsNullOrWhiteSpace(src.ExternalSourceId)) return Bad("externalSourceId","External source id is required."); if(src.ExternalSourceId.Trim().Length>240)return Bad("externalSourceId","External source id is too long."); return null; }
    private static async Task<List<ClimateMappingDto>> ToMappingDtos(HomeOpsDbContext db, IReadOnlyCollection<RoomClimateSourceMapping> list, CancellationToken ct){ var pairs=list.Select(m=>new{m.ProviderId,m.ExternalSourceId}).Distinct().ToList(); var all=await db.RoomClimateSourceMappings.AsNoTracking().Where(m=>!m.IsArchived).ToListAsync(ct); return list.Select(m=>{var shared=IsHeatingRole(m.SourceRole)?all.Where(o=>o.Id!=m.Id&&o.ProviderId==m.ProviderId&&o.ExternalSourceId==m.ExternalSourceId).Select(o=>o.RoomId).Distinct().ToList():[]; return new ClimateMappingDto(m.Id,m.RoomId,m.ProviderId,m.SourceRole,new ExternalSourceReferenceDto(m.ExternalSourceId,m.ExternalDisplayName,m.ExternalSourceKind,m.ExternalAreaId,m.ExternalAreaName,m.ExternalDeviceId,m.ExternalDeviceName),m.Priority,m.IsEnabled,m.IsArchived,m.ArchivedUtc,m.Health,m.LastCheckedUtc,m.LastSuccessfulUtc,m.DiagnosticSummary,shared.Count>0,shared,m.CreatedUtc,m.UpdatedUtc);}).ToList(); }
    private static bool IsHeatingRole(ClimateSourceRole r)=>r is ClimateSourceRole.HeatingControlTemperature or ClimateSourceRole.HeatingStatus or ClimateSourceRole.HeatingTargetTemperature or ClimateSourceRole.HeatingControl;
    private static ClimateProviderDto ToProviderDto(ClimateProvider p)=>new(p.Id,p.DisplayName,p.ProviderType,p.IsEnabled,p.IsArchived,p.ArchivedUtc,p.ExternalInstanceReference,p.DiagnosticMetadata,p.CreatedUtc,p.UpdatedUtc);
    private static string? Clean(string? value,int max){var c=value?.Trim(); if(string.IsNullOrWhiteSpace(c))return null; return c.Length>max?c[..max]:c;}
    private static IResult Bad(string field,string message)=>Results.BadRequest(new Dictionary<string,string[]>{{field,[message]}});
}
