using HomeOps.Api.Data;
using HomeOps.Api.Households;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HomeOps.Api.FloorPlans;

public static class FloorPlanAssetEndpoints
{
    public static IEndpointRouteBuilder MapFloorPlanAssetEndpoints(this IEndpointRouteBuilder app)
    {
        var floors=app.MapGroup("/api/floors/{floorId:guid}/floor-plan-assets").WithTags("Floor Plan Assets");
        floors.MapGet("/", List).WithName("ListFloorPlanAssets").Produces<IReadOnlyCollection<FloorPlanAssetDto>>().Produces(404);
        floors.MapPost("/", Upload).DisableAntiforgery().WithName("UploadFloorPlanAsset").Produces<FloorPlanAssetUploadResult>(201).ProducesValidationProblem().Produces(404);
        floors.MapGet("/active", Active).WithName("GetActiveFloorPlanAsset").Produces<FloorPlanAssetDto>().Produces(404);
        floors.MapPost("/{assetId:guid}/activate", Activate).WithName("ActivateFloorPlanAsset").Produces<FloorPlanAssetDto>().ProducesValidationProblem().Produces(404);
        floors.MapPost("/rollback", Rollback).WithName("RollbackFloorPlanAsset").Produces<FloorPlanAssetDto>().ProducesValidationProblem().Produces(404);
        var assets=app.MapGroup("/api/floor-plan-assets").WithTags("Floor Plan Assets");
        assets.MapGet("/{assetId:guid}", Get).WithName("GetFloorPlanAsset").Produces<FloorPlanAssetDto>().Produces(404);
        assets.MapPost("/{assetId:guid}/archive", Archive).WithName("ArchiveFloorPlanAsset").Produces(204).ProducesValidationProblem().Produces(404);
        assets.MapPost("/{assetId:guid}/mark-missing", MarkMissing).WithName("MarkFloorPlanAssetMissing").Produces<FloorPlanAssetDto>().Produces(404);
        assets.MapGet("/{assetId:guid}/derivative", Derivative).WithName("GetFloorPlanAssetDerivative").Produces(404);
        return app;
    }
    private static async Task<IResult> List(Guid floorId, HomeOpsDbContext db, CancellationToken ct){ if(!await FloorOk(db,floorId,ct,true))return Results.NotFound(); var a=await db.FloorPlanAssets.AsNoTracking().Where(x=>x.FloorId==floorId&&x.HouseholdId==SeedHousehold.Id).OrderByDescending(x=>x.CreatedUtc).ToListAsync(ct); return Results.Ok(a.Select(Dto).ToList());}
    private static async Task<IResult> Get(Guid assetId, HomeOpsDbContext db, CancellationToken ct)=> await db.FloorPlanAssets.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==assetId&&x.HouseholdId==SeedHousehold.Id,ct) is {} a ? Results.Ok(Dto(a)) : Results.NotFound();
    private static async Task<IResult> Active(Guid floorId, HomeOpsDbContext db, CancellationToken ct)=> await db.FloorPlanAssets.AsNoTracking().FirstOrDefaultAsync(x=>x.FloorId==floorId&&x.HouseholdId==SeedHousehold.Id&&x.State==FloorPlanAssetState.Active,ct) is {} a ? Results.Ok(Dto(a)) : Results.NotFound();
    private static async Task<IResult> Upload(Guid floorId, [FromForm] IFormFile file, HomeOpsDbContext db, FloorPlanAssetService svc, CancellationToken ct)
    { var floor=await db.Floors.AsNoTracking().FirstOrDefaultAsync(f=>f.Id==floorId&&f.HouseholdId==SeedHousehold.Id,ct); if(floor is null)return Results.NotFound(); if(floor.IsArchived||!floor.IsEnabled)return Bad("floorId","Floor plan assets require an active Floor."); ValidatedFloorPlanUpload v; try{v=await svc.ValidateAsync(file,ct);}catch(Exception e) when(e is InvalidOperationException or IOException){return Bad("file",e.Message);} var now=DateTimeOffset.UtcNow; var active=await db.FloorPlanAssets.AsNoTracking().FirstOrDefaultAsync(a=>a.FloorId==floorId&&a.HouseholdId==SeedHousehold.Id&&a.State==FloorPlanAssetState.Active,ct); var asset=new FloorPlanAsset{Id=Guid.NewGuid(),HouseholdId=SeedHousehold.Id,FloorId=floorId,OriginalFilename=v.OriginalFilename,DetectedMediaType=v.MediaType,ContentHash=v.Hash,SourceWidth=v.SourceWidth,SourceHeight=v.SourceHeight,CoordinateBasisWidth=v.BasisWidth,CoordinateBasisHeight=v.BasisHeight,AspectRatio=v.BasisWidth/v.BasisHeight,State=FloorPlanAssetState.Validated,ReplacementOfAssetId=active?.Id,UploadedUtc=now,CreatedUtc=now,UpdatedUtc=now,ValidationSummary=v.Summary}; var refs=await svc.StoreAsync(SeedHousehold.Id,asset.Id,v,ct); asset.SourceContentReference=refs.SourceRef; asset.DerivativeContentReference=refs.DerivativeRef; db.FloorPlanAssets.Add(asset); await db.SaveChangesAsync(ct); return Results.Created($"/api/floor-plan-assets/{asset.Id}", new FloorPlanAssetUploadResult(Dto(asset))); }
    private static async Task<IResult> Activate(Guid floorId, Guid assetId, HomeOpsDbContext db, FloorPlanAssetService svc, CancellationToken ct)
    { await using var tx=db.Database.IsRelational()?await db.Database.BeginTransactionAsync(ct):null; var asset=await db.FloorPlanAssets.FirstOrDefaultAsync(a=>a.Id==assetId&&a.FloorId==floorId&&a.HouseholdId==SeedHousehold.Id,ct); if(asset is null)return Results.NotFound(); if(asset.State!=FloorPlanAssetState.Validated)return Bad("state","Only Validated assets may activate."); var currentActive=await db.FloorPlanAssets.AsNoTracking().FirstOrDefaultAsync(a=>a.FloorId==floorId&&a.HouseholdId==SeedHousehold.Id&&a.State==FloorPlanAssetState.Active,ct); if(currentActive is not null && asset.ReplacementOfAssetId is not null)return Bad("assetId","Replacement assets require floor-plan replacement review activation."); if(!svc.Exists(asset.DerivativeContentReference)){asset.State=FloorPlanAssetState.Missing;asset.DerivativeAvailability=FloorPlanAssetAvailability.Missing;await db.SaveChangesAsync(ct);return Bad("assetId","The safe derivative content is missing; asset cannot activate.");} var active=await db.FloorPlanAssets.Where(a=>a.FloorId==floorId&&a.HouseholdId==SeedHousehold.Id&&a.State==FloorPlanAssetState.Active).ToListAsync(ct); foreach(var old in active){ old.State=FloorPlanAssetState.Replaced; old.UpdatedUtc=DateTimeOffset.UtcNow; var affected=await db.RoomOverlays.Where(o=>o.FloorPlanAssetId==old.Id&&o.State==RoomOverlayState.Trusted).ToListAsync(ct); foreach(var overlay in affected){overlay.State=RoomOverlayState.NeedsReview; overlay.UpdatedUtc=old.UpdatedUtc;} } asset.State=FloorPlanAssetState.Active; asset.UpdatedUtc=DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); if(tx is not null)await tx.CommitAsync(ct); return Results.Ok(Dto(asset)); }
    private static async Task<IResult> Rollback(Guid floorId, HomeOpsDbContext db, FloorPlanAssetService svc, CancellationToken ct){ await using var tx=db.Database.IsRelational()?await db.Database.BeginTransactionAsync(ct):null; var current=await db.FloorPlanAssets.FirstOrDefaultAsync(a=>a.FloorId==floorId&&a.HouseholdId==SeedHousehold.Id&&a.State==FloorPlanAssetState.Active,ct); var previous=await db.FloorPlanAssets.Where(a=>a.FloorId==floorId&&a.HouseholdId==SeedHousehold.Id&&a.State==FloorPlanAssetState.Replaced).OrderByDescending(a=>a.UpdatedUtc).FirstOrDefaultAsync(ct); if(previous is null)return Bad("assetId","No retained replaced floor plan asset is available for rollback."); if(!svc.Exists(previous.DerivativeContentReference))return Bad("assetId","Retained rollback asset content is missing."); if(current is not null){current.State=FloorPlanAssetState.Replaced;current.UpdatedUtc=DateTimeOffset.UtcNow;} previous.State=FloorPlanAssetState.Active; previous.UpdatedUtc=DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); if(tx is not null) await tx.CommitAsync(ct); return Results.Ok(Dto(previous));}
    private static async Task<IResult> Archive(Guid assetId, HomeOpsDbContext db, CancellationToken ct){ var a=await db.FloorPlanAssets.FirstOrDefaultAsync(x=>x.Id==assetId&&x.HouseholdId==SeedHousehold.Id,ct); if(a is null)return Results.NotFound(); a.State=FloorPlanAssetState.Archived; a.UpdatedUtc=DateTimeOffset.UtcNow; var overlays=await db.RoomOverlays.Where(o=>o.FloorPlanAssetId==a.Id&&o.State==RoomOverlayState.Trusted).ToListAsync(ct); foreach(var overlay in overlays){overlay.State=RoomOverlayState.NeedsReview; overlay.UpdatedUtc=a.UpdatedUtc;} await db.SaveChangesAsync(ct); return Results.NoContent();}
    private static async Task<IResult> MarkMissing(Guid assetId, HomeOpsDbContext db, CancellationToken ct){ var a=await db.FloorPlanAssets.FirstOrDefaultAsync(x=>x.Id==assetId&&x.HouseholdId==SeedHousehold.Id,ct); if(a is null)return Results.NotFound(); a.State=FloorPlanAssetState.Missing; a.SourceAvailability=FloorPlanAssetAvailability.Missing; a.DerivativeAvailability=FloorPlanAssetAvailability.Missing; a.UpdatedUtc=DateTimeOffset.UtcNow; var overlays=await db.RoomOverlays.Where(o=>o.FloorPlanAssetId==a.Id&&o.State==RoomOverlayState.Trusted).ToListAsync(ct); foreach(var overlay in overlays){overlay.State=RoomOverlayState.NeedsReview; overlay.UpdatedUtc=a.UpdatedUtc;} await db.SaveChangesAsync(ct); return Results.Ok(Dto(a));}
    private static async Task<IResult> Derivative(Guid assetId, HomeOpsDbContext db, FloorPlanAssetService svc, CancellationToken ct){ var a=await db.FloorPlanAssets.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==assetId&&x.HouseholdId==SeedHousehold.Id,ct); if(a is null||a.State is FloorPlanAssetState.Invalid or FloorPlanAssetState.Missing)return Results.NotFound(); var b=await svc.ReadDerivativeAsync(a,ct); return b is null?Results.NotFound():Results.File(b,a.DetectedMediaType);}
    private static async Task<bool> FloorOk(HomeOpsDbContext db,Guid id,CancellationToken ct,bool allowArchived=false)=>await db.Floors.AnyAsync(f=>f.Id==id&&f.HouseholdId==SeedHousehold.Id&&(allowArchived||(!f.IsArchived&&f.IsEnabled)),ct);
    private static FloorPlanAssetDto Dto(FloorPlanAsset a)=>new(a.Id,a.FloorId,a.OriginalFilename,a.DetectedMediaType,a.ContentHash,a.SourceWidth,a.SourceHeight,a.CoordinateBasisWidth,a.CoordinateBasisHeight,a.AspectRatio,a.State,a.ReplacementOfAssetId,a.UploadedUtc,a.CreatedUtc,a.UpdatedUtc,a.ValidationSummary,a.SourceAvailability,a.DerivativeAvailability,$"/api/floor-plan-assets/{a.Id}/derivative");
    private static IResult Bad(string field,string message)=>Results.ValidationProblem(new Dictionary<string,string[]>{{field,[message]}});
}
