using HomeOps.Api.Data;
using HomeOps.Api.Households;
using Microsoft.EntityFrameworkCore;

namespace HomeOps.Api.FloorPlans;

public static class FloorPlanReplacementReviewEndpoints
{
    public static IEndpointRouteBuilder MapFloorPlanReplacementReviewEndpoints(this IEndpointRouteBuilder app)
    {
        var g = app.MapGroup("/api/floors/{floorId:guid}/floor-plan-replacement-reviews").WithTags("Floor Plan Replacement Reviews");
        g.MapPost("/", Start).WithName("StartFloorPlanReplacementReview").Produces<FloorPlanReplacementReviewDto>(201).ProducesValidationProblem().Produces(404);
        g.MapGet("/", List).WithName("ListFloorPlanReplacementReviews").Produces<IReadOnlyCollection<FloorPlanReplacementReviewDto>>().Produces(404);
        g.MapGet("/active", Active).WithName("GetActiveFloorPlanReplacementReview").Produces<FloorPlanReplacementReviewDto>().Produces(204).Produces(404);
        g.MapGet("/{reviewId:guid}", Get).WithName("GetFloorPlanReplacementReview").Produces<FloorPlanReplacementReviewDto>().Produces(404);
        g.MapGet("/{reviewId:guid}/rooms", Items).WithName("GetFloorPlanReplacementReviewRooms").Produces<IReadOnlyCollection<FloorPlanReplacementReviewItemDto>>().Produces(404);
        g.MapPut("/{reviewId:guid}/rooms/{roomId:guid}/disposition", UpdateDisposition).WithName("UpdateFloorPlanReplacementRoomDisposition").Produces<FloorPlanReplacementReviewDto>().ProducesValidationProblem().Produces(404);
        g.MapPost("/{reviewId:guid}/rooms/{roomId:guid}/approve-reuse", ApproveReuse).WithName("ApproveFloorPlanReplacementReuse").Produces<FloorPlanReplacementReviewDto>().ProducesValidationProblem().Produces<ReplacementReviewValidationResultDto>(400).Produces(404);
        g.MapPost("/{reviewId:guid}/rooms/{roomId:guid}/replacement-overlay", AttachOverlay).WithName("AttachFloorPlanReplacementOverlay").Produces<FloorPlanReplacementReviewDto>().ProducesValidationProblem().Produces<ReplacementReviewValidationResultDto>(400).Produces(404);
        g.MapPost("/{reviewId:guid}/rooms/{roomId:guid}/reset", ResetItem).WithName("ResetFloorPlanReplacementRoomReview").Produces<FloorPlanReplacementReviewDto>().Produces(404);
        g.MapGet("/{reviewId:guid}/validation", ValidateReady).WithName("ValidateFloorPlanReplacementReview").Produces<ReplacementReviewValidationResultDto>().Produces(404);
        g.MapPost("/{reviewId:guid}/activate", Activate).WithName("ActivateFloorPlanReplacementReview").Produces<FloorPlanReplacementReviewDto>().Produces<ReplacementReviewValidationResultDto>(400).ProducesValidationProblem().Produces(404);
        g.MapPost("/{reviewId:guid}/cancel", Cancel).WithName("CancelFloorPlanReplacementReview").Produces<FloorPlanReplacementReviewDto>().ProducesValidationProblem().Produces(404);
        g.MapGet("/{reviewId:guid}/rollback", RollbackAvailability).WithName("GetFloorPlanReplacementRollbackAvailability").Produces<FloorPlanReplacementRollbackAvailabilityDto>().Produces(404);
        g.MapPost("/{reviewId:guid}/rollback", Rollback).WithName("RollbackFloorPlanReplacementReview").Produces<FloorPlanReplacementReviewDto>().ProducesValidationProblem().Produces(404);
        return app;
    }

    static async Task<IResult> Start(Guid floorId, StartFloorPlanReplacementReviewRequest req, HomeOpsDbContext db, FloorPlanAssetService assets, CancellationToken ct)
    {
        var floor = await db.Floors.AsNoTracking().FirstOrDefaultAsync(f => f.Id == floorId && f.HouseholdId == SeedHousehold.Id, ct);
        if (floor is null) return Results.NotFound();
        if (floor.IsArchived || !floor.IsEnabled) return Bad("floorId", "Replacement review requires an active Floor.");
        if (await db.FloorPlanReplacementReviews.AnyAsync(r => r.FloorId == floorId && (r.Status == FloorPlanReplacementReviewStatus.Draft || r.Status == FloorPlanReplacementReviewStatus.InReview || r.Status == FloorPlanReplacementReviewStatus.ReadyToActivate), ct)) return Bad("floorId", "This Floor already has an active replacement review.");
        var current = await db.FloorPlanAssets.AsNoTracking().FirstOrDefaultAsync(a => a.FloorId == floorId && a.HouseholdId == SeedHousehold.Id && a.State == FloorPlanAssetState.Active, ct);
        if (current is null) return Bad("currentAssetId", "A current Active asset is required before replacement review can start.");
        var replacement = await db.FloorPlanAssets.AsNoTracking().FirstOrDefaultAsync(a => a.Id == req.ReplacementAssetId && a.HouseholdId == SeedHousehold.Id, ct);
        if (replacement is null) return Results.NotFound();
        if (replacement.FloorId != floorId || replacement.State != FloorPlanAssetState.Validated) return Bad("replacementAssetId", "Replacement asset must belong to the Floor and be Validated.");
        if (!assets.Exists(replacement.DerivativeContentReference) || replacement.DerivativeAvailability != FloorPlanAssetAvailability.Available) return Bad("replacementAssetId", "Replacement asset derivative content is missing.");
        var now = DateTimeOffset.UtcNow;
        var compatible = current.CoordinateBasisWidth == replacement.CoordinateBasisWidth && current.CoordinateBasisHeight == replacement.CoordinateBasisHeight;
        var aspect = current.AspectRatio == replacement.AspectRatio;
        var review = new FloorPlanReplacementReview { Id = Guid.NewGuid(), HouseholdId = SeedHousehold.Id, FloorId = floorId, CurrentAssetId = current.Id, ReplacementAssetId = replacement.Id, Status = FloorPlanReplacementReviewStatus.InReview, SameCoordinateBasisDimensions = compatible, SameAspectRatio = aspect, SameDerivativeBasis = compatible && aspect, ReuseCandidatesAvailable = compatible && aspect, CreatedUtc = now, UpdatedUtc = now };
        var trusted = await db.RoomOverlays.AsNoTracking().Where(o => o.FloorPlanAssetId == current.Id && o.State == RoomOverlayState.Trusted).ToListAsync(ct);
        foreach (var room in await db.Rooms.AsNoTracking().Where(r => r.FloorId == floorId && r.HouseholdId == SeedHousehold.Id && r.IsEnabled && !r.IsArchived).ToListAsync(ct))
            review.Items.Add(new FloorPlanReplacementReviewItem { Id = Guid.NewGuid(), ReviewId = review.Id, HouseholdId = SeedHousehold.Id, FloorId = floorId, RoomId = room.Id, Disposition = RoomReplacementDisposition.PendingReview, ReuseCandidateOverlayId = review.ReuseCandidatesAvailable ? trusted.FirstOrDefault(o => o.RoomId == room.Id)?.Id : null, CreatedUtc = now, UpdatedUtc = now });
        db.FloorPlanReplacementReviews.Add(review); await db.SaveChangesAsync(ct); return Results.Created($"/api/floors/{floorId}/floor-plan-replacement-reviews/{review.Id}", await Dto(db, review.Id, ct));
    }
    static async Task<IResult> List(Guid floorId, HomeOpsDbContext db, CancellationToken ct) => !await db.Floors.AnyAsync(f => f.Id == floorId && f.HouseholdId == SeedHousehold.Id, ct) ? Results.NotFound() : Results.Ok(await Dtos(db, db.FloorPlanReplacementReviews.AsNoTracking().Where(r => r.FloorId == floorId && r.HouseholdId == SeedHousehold.Id).OrderByDescending(r => r.CreatedUtc), ct));
    static async Task<IResult> Active(Guid floorId, HomeOpsDbContext db, CancellationToken ct)
    {
        if (!await db.Floors.AnyAsync(f => f.Id == floorId && f.HouseholdId == SeedHousehold.Id, ct)) return Results.NotFound();
        var review = await db.FloorPlanReplacementReviews.AsNoTracking().Where(r => r.FloorId == floorId && r.HouseholdId == SeedHousehold.Id && (r.Status == FloorPlanReplacementReviewStatus.Draft || r.Status == FloorPlanReplacementReviewStatus.InReview || r.Status == FloorPlanReplacementReviewStatus.ReadyToActivate)).OrderByDescending(r => r.UpdatedUtc).FirstOrDefaultAsync(ct);
        return review is null ? Results.NoContent() : Results.Ok(await Dto(db, review.Id, ct));
    }
    static async Task<IResult> Get(Guid floorId, Guid reviewId, HomeOpsDbContext db, CancellationToken ct) => await Dto(db, reviewId, ct) is { } d && d.FloorId == floorId ? Results.Ok(d) : Results.NotFound();
    static async Task<IResult> Items(Guid floorId, Guid reviewId, HomeOpsDbContext db, CancellationToken ct) => await Dto(db, reviewId, ct) is { } d && d.FloorId == floorId ? Results.Ok(d.Items) : Results.NotFound();
    static async Task<IResult> UpdateDisposition(Guid floorId, Guid reviewId, Guid roomId, UpdateRoomReplacementDispositionRequest req, HomeOpsDbContext db, CancellationToken ct) { var item = await Item(db, floorId, reviewId, roomId, ct); if (item is null) return Results.NotFound(); if (req.Disposition == RoomReplacementDisposition.PendingReview || req.Disposition == RoomReplacementDisposition.ApprovedReuse) return Bad("disposition", "Use reset or approve operations for PendingReview and ApprovedReuse."); item.Disposition = req.Disposition; item.FallbackReason = req.FallbackReason; item.ReplacementOverlayId = null; item.LabelAnchorApproved = false; Touch(item); await TouchReview(db, reviewId, ct); await db.SaveChangesAsync(ct); return Results.Ok(await Dto(db, reviewId, ct)); }
    static async Task<IResult> ApproveReuse(Guid floorId, Guid reviewId, Guid roomId, ApproveReuseCandidateRequest req, HomeOpsDbContext db, CancellationToken ct) { var (review,item)=await ReviewItem(db,floorId,reviewId,roomId,ct); if (item is null||review is null) return Results.NotFound(); if (!review.ReuseCandidatesAvailable || item.ReuseCandidateOverlayId is null) return Bad("roomId", "No compatible reuse candidate is available for this Room."); var cand=await db.RoomOverlays.AsNoTracking().FirstAsync(o=>o.Id==item.ReuseCandidateOverlayId,ct); var overlay=new RoomOverlay{Id=Guid.NewGuid(),HouseholdId=SeedHousehold.Id,FloorId=floorId,RoomId=roomId,FloorPlanAssetId=review.ReplacementAssetId,State=RoomOverlayState.Valid,PolygonJson=cand.PolygonJson,LabelAnchorX=req.PreserveLabelAnchor?cand.LabelAnchorX:null,LabelAnchorY=req.PreserveLabelAnchor?cand.LabelAnchorY:null,CreatedUtc=DateTimeOffset.UtcNow,UpdatedUtc=DateTimeOffset.UtcNow}; var v=await ValidateCandidate(db, overlay, reviewId, roomId, ct); if(v.Count>0)return Results.BadRequest(new ReplacementReviewValidationResultDto(reviewId,false,v)); db.RoomOverlays.Add(overlay); item.ReplacementOverlayId=overlay.Id; item.Disposition=RoomReplacementDisposition.ApprovedReuse; item.LabelAnchorApproved=req.PreserveLabelAnchor; Touch(item); await TouchReview(db,reviewId,ct); await db.SaveChangesAsync(ct); return Results.Ok(await Dto(db,reviewId,ct)); }
    static async Task<IResult> AttachOverlay(Guid floorId, Guid reviewId, Guid roomId, AttachReplacementOverlayRequest req, HomeOpsDbContext db, CancellationToken ct){ var (review,item)=await ReviewItem(db,floorId,reviewId,roomId,ct); if(item is null||review is null)return Results.NotFound(); var o=await db.RoomOverlays.FirstOrDefaultAsync(x=>x.Id==req.OverlayId&&x.HouseholdId==SeedHousehold.Id,ct); if(o is null)return Results.NotFound(); if(o.FloorId!=floorId||o.RoomId!=roomId||o.FloorPlanAssetId!=review.ReplacementAssetId)return Bad("overlayId","Overlay must link to this Floor, Room, and replacement asset."); if(o.State!=RoomOverlayState.Valid)return Bad("overlayId","Only Valid replacement overlays can be approved for activation."); if(req.Approve&&item.ReplacementOverlayId is Guid existing&&existing!=o.Id&&item.Disposition==RoomReplacementDisposition.ApprovedReuse)return Bad("roomId","This Room already has an approved replacement overlay; reset it before approving another."); var v=await ValidateCandidate(db,o,reviewId,roomId,ct); if(v.Count>0)return Results.BadRequest(new ReplacementReviewValidationResultDto(reviewId,false,v)); o.UpdatedUtc=DateTimeOffset.UtcNow; item.ReplacementOverlayId=o.Id; item.Disposition=req.Approve?RoomReplacementDisposition.ApprovedReuse:RoomReplacementDisposition.PendingReview; item.LabelAnchorApproved=req.PreserveLabelAnchor; if(!req.PreserveLabelAnchor){o.LabelAnchorX=o.LabelAnchorY=null;} Touch(item); await TouchReview(db,reviewId,ct); await db.SaveChangesAsync(ct); return Results.Ok(await Dto(db,reviewId,ct)); }
    static async Task<IResult> ResetItem(Guid floorId, Guid reviewId, Guid roomId, HomeOpsDbContext db, CancellationToken ct){ var item=await Item(db,floorId,reviewId,roomId,ct); if(item is null)return Results.NotFound(); item.Disposition=RoomReplacementDisposition.PendingReview; item.ReplacementOverlayId=null; item.FallbackReason=null; item.LabelAnchorApproved=false; Touch(item); await TouchReview(db,reviewId,ct); await db.SaveChangesAsync(ct); return Results.Ok(await Dto(db,reviewId,ct)); }
    static async Task<IResult> ValidateReady(Guid floorId, Guid reviewId, HomeOpsDbContext db, FloorPlanAssetService svc, CancellationToken ct){ var b=await ActivationBlockers(db,floorId,reviewId,svc,ct); return b is null?Results.NotFound():Results.Ok(new ReplacementReviewValidationResultDto(reviewId,b.Count==0,b)); }
    static async Task<IResult> Activate(Guid floorId, Guid reviewId, HomeOpsDbContext db, FloorPlanAssetService svc, CancellationToken ct){ await using var tx=db.Database.IsRelational()?await db.Database.BeginTransactionAsync(ct):null; var blockers=await ActivationBlockers(db,floorId,reviewId,svc,ct); if(blockers is null)return Results.NotFound(); if(blockers.Count>0)return Results.BadRequest(new ReplacementReviewValidationResultDto(reviewId,false,blockers)); var review=await db.FloorPlanReplacementReviews.Include(r=>r.Items).FirstAsync(r=>r.Id==reviewId,ct); var now=DateTimeOffset.UtcNow; var old=await db.FloorPlanAssets.FirstAsync(a=>a.Id==review.CurrentAssetId,ct); var repl=await db.FloorPlanAssets.FirstAsync(a=>a.Id==review.ReplacementAssetId,ct); old.State=FloorPlanAssetState.Replaced; old.UpdatedUtc=now; repl.State=FloorPlanAssetState.Active; repl.UpdatedUtc=now; foreach(var o in await db.RoomOverlays.Where(o=>o.FloorPlanAssetId==old.Id&&o.State==RoomOverlayState.Trusted).ToListAsync(ct)){o.UpdatedUtc=now;} foreach(var id in review.Items.Where(i=>i.Disposition==RoomReplacementDisposition.ApprovedReuse).Select(i=>i.ReplacementOverlayId!.Value)){var o=await db.RoomOverlays.FirstAsync(x=>x.Id==id,ct); o.State=RoomOverlayState.Trusted; o.UpdatedUtc=now;} review.Status=FloorPlanReplacementReviewStatus.Activated; review.ActivatedAssetId=repl.Id; review.RollbackAssetId=old.Id; review.CompletedUtc=review.ActivatedUtc=review.UpdatedUtc=now; await db.SaveChangesAsync(ct); if(tx is not null)await tx.CommitAsync(ct); return Results.Ok(await Dto(db,reviewId,ct)); }
    static async Task<IResult> Cancel(Guid floorId, Guid reviewId, HomeOpsDbContext db, CancellationToken ct){ var r=await db.FloorPlanReplacementReviews.FirstOrDefaultAsync(r=>r.Id==reviewId&&r.FloorId==floorId&&r.HouseholdId==SeedHousehold.Id,ct); if(r is null)return Results.NotFound(); if(r.Status==FloorPlanReplacementReviewStatus.Activated)return Bad("reviewId","Activated replacement reviews cannot be cancelled."); if(r.Status==FloorPlanReplacementReviewStatus.Cancelled)return Bad("reviewId","Replacement review is already cancelled."); r.Status=FloorPlanReplacementReviewStatus.Cancelled; r.CancelledUtc=r.CompletedUtc=r.UpdatedUtc=DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); return Results.Ok(await Dto(db,reviewId,ct)); }
    static async Task<IResult> RollbackAvailability(Guid floorId, Guid reviewId, HomeOpsDbContext db, FloorPlanAssetService svc, CancellationToken ct)
    {
        var r = await db.FloorPlanReplacementReviews.AsNoTracking().FirstOrDefaultAsync(r => r.Id == reviewId && r.FloorId == floorId && r.HouseholdId == SeedHousehold.Id, ct);
        if (r is null) return Results.NotFound();
        var blockers = await RollbackBlockers(db, r, svc, ct);
        return Results.Ok(new FloorPlanReplacementRollbackAvailabilityDto(reviewId, blockers.Count == 0, r.ActivatedAssetId, r.RollbackAssetId, blockers));
    }
    static async Task<IResult> Rollback(Guid floorId, Guid reviewId, HomeOpsDbContext db, FloorPlanAssetService svc, CancellationToken ct){ await using var tx=db.Database.IsRelational()?await db.Database.BeginTransactionAsync(ct):null; var r=await db.FloorPlanReplacementReviews.Include(r=>r.Items).FirstOrDefaultAsync(r=>r.Id==reviewId&&r.FloorId==floorId&&r.HouseholdId==SeedHousehold.Id&&r.Status==FloorPlanReplacementReviewStatus.Activated,ct); if(r is null)return Results.NotFound(); var blockers=await RollbackBlockers(db,r,svc,ct); if(blockers.Count>0)return Bad("reviewId","Rollback content is missing or no longer matches the activated review."); var prev=await db.FloorPlanAssets.FirstAsync(a=>a.Id==r.RollbackAssetId,ct); var cur=await db.FloorPlanAssets.FirstAsync(a=>a.Id==r.ActivatedAssetId&&a.State==FloorPlanAssetState.Active,ct); foreach(var o in await db.RoomOverlays.Where(o=>o.FloorPlanAssetId==cur.Id&&o.State==RoomOverlayState.Trusted).ToListAsync(ct)){o.State=RoomOverlayState.Valid;o.UpdatedUtc=DateTimeOffset.UtcNow;} cur.State=FloorPlanAssetState.Replaced; prev.State=FloorPlanAssetState.Active; cur.UpdatedUtc=prev.UpdatedUtc=DateTimeOffset.UtcNow; r.UpdatedUtc=DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); if(tx is not null)await tx.CommitAsync(ct); return Results.Ok(await Dto(db,reviewId,ct)); }

    static async Task<List<RoomOverlayValidationIssue>?> ActivationBlockers(HomeOpsDbContext db, Guid floorId, Guid reviewId, FloorPlanAssetService svc, CancellationToken ct){ var r=await db.FloorPlanReplacementReviews.Include(x=>x.Items).FirstOrDefaultAsync(x=>x.Id==reviewId&&x.FloorId==floorId&&x.HouseholdId==SeedHousehold.Id,ct); if(r is null)return null; var b=new List<RoomOverlayValidationIssue>(); var active=await db.FloorPlanAssets.AsNoTracking().FirstOrDefaultAsync(a=>a.Id==r.CurrentAssetId&&a.State==FloorPlanAssetState.Active,ct); if(active is null)b.Add(new("StaleActiveAsset","The current Active asset has changed.")); var repl=await db.FloorPlanAssets.AsNoTracking().FirstOrDefaultAsync(a=>a.Id==r.ReplacementAssetId&&a.State==FloorPlanAssetState.Validated,ct); if(repl is null)b.Add(new("InvalidReplacementAsset","Replacement asset must still be Validated.")); else if(!svc.Exists(repl.DerivativeContentReference))b.Add(new("MissingDerivative","Replacement derivative content is missing.")); var rooms=await db.Rooms.AsNoTracking().Where(room=>room.FloorId==floorId&&room.HouseholdId==SeedHousehold.Id&&room.IsEnabled&&!room.IsArchived).Select(room=>room.Id).ToListAsync(ct); foreach(var room in rooms){var item=r.Items.SingleOrDefault(i=>i.RoomId==room); if(item is null)b.Add(new("MissingRoomItem","Every enabled Room needs a review item.",null,room)); else if(item.Disposition==RoomReplacementDisposition.PendingReview)b.Add(new("PendingRoom","Every enabled Room needs an explicit disposition.",null,room)); else if(item.Disposition==RoomReplacementDisposition.ApprovedReuse && item.ReplacementOverlayId is null)b.Add(new("MissingApprovedOverlay","Approved Rooms need replacement geometry.",null,room)); else if(item.Disposition==RoomReplacementDisposition.RedrawRequired)b.Add(new("RedrawRequired","Rooms marked redraw required need newly approved replacement geometry before activation.",null,room));}
        foreach(var item in r.Items.Where(i=>i.Disposition==RoomReplacementDisposition.ApprovedReuse&&i.ReplacementOverlayId is not null)){var o=await db.RoomOverlays.AsNoTracking().FirstOrDefaultAsync(o=>o.Id==item.ReplacementOverlayId,ct); if(o is null||o.FloorId!=floorId||o.RoomId!=item.RoomId||o.FloorPlanAssetId!=r.ReplacementAssetId||o.HouseholdId!=SeedHousehold.Id)b.Add(new("InvalidApprovedOverlay","Approved overlay must link to the review Floor, Room, replacement Asset, and Household.",item.ReplacementOverlayId,item.RoomId)); else b.AddRange(await ValidateCandidate(db,o,reviewId,item.RoomId,ct));} return b; }
    static async Task<List<RoomOverlayValidationIssue>> ValidateCandidate(HomeOpsDbContext db, RoomOverlay o, Guid reviewId, Guid roomId, CancellationToken ct){ var v=await RoomOverlayEndpoints.Validate(db,o,false,ct); var b=v.Blockers.Where(issue => issue.Code != "NonUsableAsset").ToList(); var pts=RoomOverlayEndpoints.Points(o); var others=await db.FloorPlanReplacementReviewItems.AsNoTracking().Where(i=>i.ReviewId==reviewId&&i.RoomId!=roomId&&i.Disposition==RoomReplacementDisposition.ApprovedReuse&&i.ReplacementOverlayId!=null).Select(i=>i.ReplacementOverlayId!.Value).ToListAsync(ct); foreach(var other in await db.RoomOverlays.AsNoTracking().Where(x=>others.Contains(x.Id)).ToListAsync(ct)) if(RoomOverlayGeometry.HasPositiveOverlap(pts,RoomOverlayEndpoints.Points(other))) b.Add(new("ApprovedOverlayOverlap","Approved replacement overlays cannot overlap by positive area.",other.Id,other.RoomId)); return b; }
    static async Task<(FloorPlanReplacementReview?,FloorPlanReplacementReviewItem?)> ReviewItem(HomeOpsDbContext db,Guid floorId,Guid reviewId,Guid roomId,CancellationToken ct){ var r=await db.FloorPlanReplacementReviews.Include(r=>r.Items).FirstOrDefaultAsync(r=>r.Id==reviewId&&r.FloorId==floorId&&r.HouseholdId==SeedHousehold.Id,ct); return (r,r?.Items.SingleOrDefault(i=>i.RoomId==roomId)); }
    static async Task<FloorPlanReplacementReviewItem?> Item(HomeOpsDbContext db,Guid floorId,Guid reviewId,Guid roomId,CancellationToken ct)=>(await ReviewItem(db,floorId,reviewId,roomId,ct)).Item2;
    static void Touch(FloorPlanReplacementReviewItem i){ i.UpdatedUtc=DateTimeOffset.UtcNow; }
    static async Task TouchReview(HomeOpsDbContext db, Guid id, CancellationToken ct){ var r=await db.FloorPlanReplacementReviews.FirstAsync(r=>r.Id==id,ct); r.UpdatedUtc=DateTimeOffset.UtcNow; }
    static async Task<List<RoomOverlayValidationIssue>> RollbackBlockers(HomeOpsDbContext db, FloorPlanReplacementReview r, FloorPlanAssetService svc, CancellationToken ct)
    {
        var blockers = new List<RoomOverlayValidationIssue>();
        if (r.Status != FloorPlanReplacementReviewStatus.Activated) blockers.Add(new("ReviewNotActivated", "Only activated replacement reviews can be rolled back."));
        var prev = await db.FloorPlanAssets.AsNoTracking().FirstOrDefaultAsync(a => a.Id == r.RollbackAssetId && a.HouseholdId == SeedHousehold.Id, ct);
        var cur = await db.FloorPlanAssets.AsNoTracking().FirstOrDefaultAsync(a => a.Id == r.ActivatedAssetId && a.HouseholdId == SeedHousehold.Id && a.State == FloorPlanAssetState.Active, ct);
        if (prev is null) blockers.Add(new("MissingRollbackAsset", "The previous floor-plan asset is no longer available."));
        else if (!svc.Exists(prev.DerivativeContentReference)) blockers.Add(new("MissingRollbackDerivative", "The previous floor-plan derivative content is missing."));
        if (cur is null) blockers.Add(new("MissingActivatedAsset", "The activated replacement asset is no longer current."));
        return blockers;
    }
    static async Task<FloorPlanReplacementReviewDto?> Dto(HomeOpsDbContext db, Guid id, CancellationToken ct)=> (await Dtos(db, db.FloorPlanReplacementReviews.AsNoTracking().Where(r=>r.Id==id&&r.HouseholdId==SeedHousehold.Id), ct)).FirstOrDefault();
    static async Task<List<FloorPlanReplacementReviewDto>> Dtos(HomeOpsDbContext db, IQueryable<FloorPlanReplacementReview> query, CancellationToken ct)
    {
        var reviews = await query.Include(r => r.Items).ToListAsync(ct);
        var roomIds = reviews.SelectMany(r => r.Items).Select(i => i.RoomId).Distinct().ToList();
        var rooms = await db.Rooms.AsNoTracking().Where(r => roomIds.Contains(r.Id)).ToDictionaryAsync(r => r.Id, ct);
        return reviews.Select(r => ToDto(r, rooms)).ToList();
    }
    static FloorPlanReplacementReviewDto ToDto(FloorPlanReplacementReview r, IReadOnlyDictionary<Guid, Room> rooms)=>new(r.Id,r.HouseholdId,r.FloorId,r.CurrentAssetId,r.ReplacementAssetId,r.Status,new FloorPlanReplacementCompatibilityDto(r.SameCoordinateBasisDimensions,r.SameAspectRatio,r.SameDerivativeBasis,r.ReuseCandidatesAvailable),r.Status==FloorPlanReplacementReviewStatus.Activated&&r.RollbackAssetId is not null,r.ActivatedAssetId,r.RollbackAssetId,r.CreatedUtc,r.UpdatedUtc,r.CompletedUtc,r.ActivatedUtc,r.CancelledUtc,r.Items.OrderBy(i=>rooms.TryGetValue(i.RoomId,out var room)?room.SortOrder:int.MaxValue).ThenBy(i=>rooms.TryGetValue(i.RoomId,out var room)?room.Name:string.Empty).Select(i=>ToItemDto(i, rooms)).ToList());
    static FloorPlanReplacementReviewItemDto ToItemDto(FloorPlanReplacementReviewItem i, IReadOnlyDictionary<Guid, Room> rooms)
    {
        rooms.TryGetValue(i.RoomId, out var room);
        return new(i.Id,i.ReviewId,i.RoomId,room?.Name ?? "Onbekende kamer",room?.RoomType ?? RoomType.Other,i.Disposition,i.ReuseCandidateOverlayId is not null,i.ReuseCandidateOverlayId,i.ReplacementOverlayId,i.LabelAnchorApproved,i.FallbackReason,i.CreatedUtc,i.UpdatedUtc);
    }
    static IResult Bad(string field,string message)=>Results.ValidationProblem(new Dictionary<string,string[]>{{field,[message]}});
}
