// <auto-generated />
using System;
using HomeOps.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HomeOps.Api.Migrations
{
    partial class AddRoomHeatingCommands
    {
        internal static void BuildResumeStrategyBaseModel(ModelBuilder modelBuilder) =>
            new AddRoomHeatingCommands().BuildTargetModel(modelBuilder);
    }

    [DbContext(typeof(HomeOpsDbContext))]
    [Migration("20260717124500_AddHomeAssistantResumeStrategyConfiguration")]
    partial class AddHomeAssistantResumeStrategyConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            AddRoomHeatingCommands.BuildResumeStrategyBaseModel(modelBuilder);

            modelBuilder.Entity("HomeOps.Api.FloorPlans.ClimateProvider", b =>
                {
                    b.Property<string>("HomeAssistantResumeClimateEntityReference")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("HomeAssistantResumePresetValue")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("HomeAssistantResumeScriptEntityReference")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("HomeAssistantResumeStrategyType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("HomeAssistantResumeStrategyUpdatedUtc")
                        .HasColumnType("timestamp with time zone");
                });
#pragma warning restore 612, 618
        }
    }
}
