// <auto-generated />
using System;
using HomeOps.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeOps.Api.Migrations
{
    [DbContext(typeof(HomeOpsDbContext))]
    [Migration("20260620145207_AddMotivationDomainFoundation")]
    partial class AddMotivationDomainFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeOps.Api.AgendaLayerSettings.AgendaLayerSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ViewType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceKey", "ViewType", "SourceId")
                        .IsUnique();

                    b.ToTable("AgendaLayerSettings", (string)null);
                });

            modelBuilder.Entity("HomeOps.Api.CalendarEvents.EventException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("EventSeriesId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("OccurrenceDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventSeriesId", "OccurrenceDate")
                        .IsUnique();

                    b.ToTable("EventExceptions", (string)null);
                });

            modelBuilder.Entity("HomeOps.Api.CalendarEvents.EventSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("EventSourceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean");

                    b.Property<string>("RecurrenceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventSourceId", "StartDate");

                    b.ToTable("EventSeries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("13131313-1313-1313-1313-131313131313"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Routine check-up",
                            EndDate = new DateOnly(2026, 6, 18),
                            EndTime = new TimeOnly(10, 15, 0),
                            EventSourceId = new Guid("12121212-1212-1212-1212-121212121212"),
                            IsAllDay = false,
                            RecurrenceType = "None",
                            StartDate = new DateOnly(2026, 6, 18),
                            StartTime = new TimeOnly(9, 30, 0),
                            Title = "Dentist Appointment",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("14141414-1414-1414-1414-141414141414"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "School hall",
                            EndDate = new DateOnly(2026, 6, 19),
                            EndTime = new TimeOnly(20, 0, 0),
                            EventSourceId = new Guid("12121212-1212-1212-1212-121212121212"),
                            IsAllDay = false,
                            RecurrenceType = "None",
                            StartDate = new DateOnly(2026, 6, 19),
                            StartTime = new TimeOnly(18, 30, 0),
                            Title = "Parent Evening",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("15151515-1515-1515-1515-151515151515"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Family trip",
                            EndDate = new DateOnly(2026, 7, 19),
                            EventSourceId = new Guid("12121212-1212-1212-1212-121212121212"),
                            IsAllDay = true,
                            RecurrenceType = "None",
                            StartDate = new DateOnly(2026, 7, 12),
                            Title = "Vacation",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("16161616-1616-1616-1616-161616161616"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EndDate = new DateOnly(2026, 6, 21),
                            EndTime = new TimeOnly(20, 10, 0),
                            EventSourceId = new Guid("12121212-1212-1212-1212-121212121212"),
                            IsAllDay = false,
                            RecurrenceType = "None",
                            StartDate = new DateOnly(2026, 6, 21),
                            StartTime = new TimeOnly(20, 0, 0),
                            Title = "Put Bins Outside",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("HomeOps.Api.CalendarEvents.EventSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsWritable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "SourceType")
                        .IsUnique();

                    b.ToTable("EventSources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsWritable = true,
                            Name = "HomeOps Calendar",
                            SourceType = "manual",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("HomeOps.Api.FamilyMembers.FamilyMember", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Glasses")
                        .HasColumnType("boolean");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("HairStyle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Presentation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ShirtColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SkinTone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Name")
                        .IsUnique();

                    b.ToTable("FamilyMembers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "alex",
                            AgeGroup = "Adult",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayColor = "#f8c8dc",
                            Glasses = false,
                            HairColor = "#3b2416",
                            HairStyle = "Long",
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Initials = "A",
                            Name = "Alex",
                            Presentation = "Feminine",
                            ShirtColor = "#f472b6",
                            SkinTone = "#c68642",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "sam",
                            AgeGroup = "Adult",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayColor = "#c7d2fe",
                            Glasses = true,
                            HairColor = "#4b5563",
                            HairStyle = "Short",
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Initials = "S",
                            Name = "Sam",
                            Presentation = "Masculine",
                            ShirtColor = "#60a5fa",
                            SkinTone = "#f1c27d",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "riley",
                            AgeGroup = "Child",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayColor = "#bbf7d0",
                            Glasses = false,
                            HairColor = "#111827",
                            HairStyle = "Curly",
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Initials = "R",
                            Name = "Riley",
                            Presentation = "Neutral",
                            ShirtColor = "#34d399",
                            SkinTone = "#8d5524",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "jordan",
                            AgeGroup = "Child",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayColor = "#fde68a",
                            Glasses = true,
                            HairColor = "#92400e",
                            HairStyle = "Top",
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Initials = "J",
                            Name = "Jordan",
                            Presentation = "Neutral",
                            ShirtColor = "#fbbf24",
                            SkinTone = "#ffdbac",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("HomeOps.Api.Households.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Households", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Home",
                            TimeZoneId = "Europe/Amsterdam",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("HomeOps.Api.Lists.List", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Name")
                        .IsUnique();

                    b.ToTable("Lists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Shopping",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Vacation Packing",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("HomeOps.Api.Lists.ListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ListId", "CreatedUtc");

                    b.ToTable("ListItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCompleted = false,
                            ListId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Text = "Bread",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCompleted = false,
                            ListId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Text = "Milk",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCompleted = false,
                            ListId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Text = "Coffee",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCompleted = false,
                            ListId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Text = "Passport",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCompleted = false,
                            ListId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Text = "Chargers",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCompleted = false,
                            ListId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Text = "Swimwear",
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("HomeOps.Api.Motivation.MotivationFamilyGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentProgress")
                        .HasColumnType("integer");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RewardLabel")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<int>("TargetCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("UnitLabel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "IsActive");

                    b.ToTable("MotivationFamilyGoals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e7e795f-66cf-4c18-87cf-1d33d1b81f01"),
                            CurrentProgress = 13,
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            RewardLabel = "Board game night together",
                            TargetCount = 20,
                            Title = "Fill the family helper path",
                            UnitLabel = "helpful actions"
                        });
                });

            modelBuilder.Entity("HomeOps.Api.Motivation.MotivationIndividualGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentProgress")
                        .HasColumnType("integer");

                    b.Property<string>("FamilyMemberId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("TargetCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("UnitLabel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("VisualKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyMemberId");

                    b.HasIndex("HouseholdId", "IsActive");

                    b.HasIndex("HouseholdId", "FamilyMemberId", "IsActive");

                    b.ToTable("MotivationIndividualGoals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e62d5716-a82a-4412-aacf-df78febbe301"),
                            CurrentProgress = 3,
                            FamilyMemberId = "alex",
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            TargetCount = 5,
                            Title = "Finish morning routine",
                            UnitLabel = "checkmarks",
                            VisualKind = "checkmarks"
                        },
                        new
                        {
                            Id = new Guid("d4c0882d-bf9a-4d4e-b925-1146e203f102"),
                            CurrentProgress = 2,
                            FamilyMemberId = "sam",
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            TargetCount = 3,
                            Title = "Help with dinner",
                            UnitLabel = "stars",
                            VisualKind = "stars"
                        },
                        new
                        {
                            Id = new Guid("7f9ad1f4-5af7-47c8-bf0a-c8232c1c6403"),
                            CurrentProgress = 2,
                            FamilyMemberId = "riley",
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            TargetCount = 4,
                            Title = "Tidy bedroom corner",
                            UnitLabel = "steps",
                            VisualKind = "progress"
                        },
                        new
                        {
                            Id = new Guid("65489d30-8f51-4181-9fae-e61254f8a4dc"),
                            CurrentProgress = 1,
                            FamilyMemberId = "jordan",
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            TargetCount = 3,
                            Title = "Notice one helpful thing",
                            UnitLabel = "stars",
                            VisualKind = "stars"
                        });
                });

            modelBuilder.Entity("HomeOps.Api.Tasks.HouseholdTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("FamilyMemberId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OwnershipKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FamilyMemberId");

                    b.HasIndex("HouseholdId", "IsCompleted", "DueDate");

                    b.ToTable("HouseholdTasks", (string)null);
                });

            modelBuilder.Entity("HomeOps.Api.WidgetLayouts.WidgetPlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("WidgetType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("WorkspaceLayoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceLayoutId", "Position")
                        .IsUnique();

                    b.ToTable("WidgetPlacements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ConfigurationJson = "{}",
                            Position = 0,
                            Size = "large",
                            WidgetType = "agenda-mvp",
                            WorkspaceLayoutId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ConfigurationJson = "{}",
                            Position = 1,
                            Size = "medium",
                            WidgetType = "shopping-list-mvp",
                            WorkspaceLayoutId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            ConfigurationJson = "{}",
                            Position = 2,
                            Size = "medium",
                            WidgetType = "welcome-text",
                            WorkspaceLayoutId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            ConfigurationJson = "{}",
                            Position = 0,
                            Size = "medium",
                            WidgetType = "house-placeholder",
                            WorkspaceLayoutId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            ConfigurationJson = "{}",
                            Position = 0,
                            Size = "medium",
                            WidgetType = "media-placeholder",
                            WorkspaceLayoutId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            ConfigurationJson = "{}",
                            Position = 0,
                            Size = "medium",
                            WidgetType = "settings-placeholder",
                            WorkspaceLayoutId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        });
                });

            modelBuilder.Entity("HomeOps.Api.WidgetLayouts.WorkspaceLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkspaceKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "WorkspaceKey")
                        .IsUnique();

                    b.ToTable("WorkspaceLayouts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WorkspaceKey = "home"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WorkspaceKey = "house"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WorkspaceKey = "media"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HouseholdId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WorkspaceKey = "settings"
                        });
                });

            modelBuilder.Entity("HomeOps.Api.CalendarEvents.EventException", b =>
                {
                    b.HasOne("HomeOps.Api.CalendarEvents.EventSeries", "EventSeries")
                        .WithMany("Exceptions")
                        .HasForeignKey("EventSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventSeries");
                });

            modelBuilder.Entity("HomeOps.Api.CalendarEvents.EventSeries", b =>
                {
                    b.HasOne("HomeOps.Api.CalendarEvents.EventSource", "EventSource")
                        .WithMany("EventSeries")
                        .HasForeignKey("EventSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventSource");
                });

            modelBuilder.Entity("HomeOps.Api.CalendarEvents.EventSource", b =>
                {
                    b.HasOne("HomeOps.Api.Households.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("HomeOps.Api.FamilyMembers.FamilyMember", b =>
                {
                    b.HasOne("HomeOps.Api.Households.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("HomeOps.Api.Lists.List", b =>
                {
                    b.HasOne("HomeOps.Api.Households.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("HomeOps.Api.Lists.ListItem", b =>
                {
                    b.HasOne("HomeOps.Api.Lists.List", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("HomeOps.Api.Motivation.MotivationFamilyGoal", b =>
                {
                    b.HasOne("HomeOps.Api.Households.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("HomeOps.Api.Motivation.MotivationIndividualGoal", b =>
                {
                    b.HasOne("HomeOps.Api.FamilyMembers.FamilyMember", "FamilyMember")
                        .WithMany()
                        .HasForeignKey("FamilyMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOps.Api.Households.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FamilyMember");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("HomeOps.Api.Tasks.HouseholdTask", b =>
                {
                    b.HasOne("HomeOps.Api.FamilyMembers.FamilyMember", null)
                        .WithMany()
                        .HasForeignKey("FamilyMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HomeOps.Api.Households.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("HomeOps.Api.WidgetLayouts.WidgetPlacement", b =>
                {
                    b.HasOne("HomeOps.Api.WidgetLayouts.WorkspaceLayout", "WorkspaceLayout")
                        .WithMany("Placements")
                        .HasForeignKey("WorkspaceLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkspaceLayout");
                });

            modelBuilder.Entity("HomeOps.Api.WidgetLayouts.WorkspaceLayout", b =>
                {
                    b.HasOne("HomeOps.Api.Households.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("HomeOps.Api.CalendarEvents.EventSeries", b =>
                {
                    b.Navigation("Exceptions");
                });

            modelBuilder.Entity("HomeOps.Api.CalendarEvents.EventSource", b =>
                {
                    b.Navigation("EventSeries");
                });

            modelBuilder.Entity("HomeOps.Api.Lists.List", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HomeOps.Api.WidgetLayouts.WorkspaceLayout", b =>
                {
                    b.Navigation("Placements");
                });
#pragma warning restore 612, 618
        }
    }
}
