import type { EventSource, NormalizedEvent } from '../events/eventSourceModel';

export const demoToday = '2026-06-18';

export const demoEventSources: readonly EventSource[] = [
  {
    id: 'manual-events',
    name: 'HomeOps Manual Events',
    type: 'manual',
    enabled: true,
    capability: 'writable',
    visibility: { visibleByDefault: true, groupName: 'Household' },
    color: { hex: '#4f46e5' },
  },
  {
    id: 'school-holidays',
    name: 'School Holidays',
    type: 'schoolHolidays',
    enabled: true,
    capability: 'readOnly',
    visibility: { visibleByDefault: true, groupName: 'Reference' },
    color: { hex: '#0891b2' },
    externalSourceId: 'demo-school-holidays',
  },
  {
    id: 'tv-series',
    name: 'TV Series',
    type: 'tvSeries',
    enabled: true,
    capability: 'readOnly',
    visibility: { visibleByDefault: true, groupName: 'Media' },
    color: { hex: '#db2777' },
    externalSourceId: 'demo-tv-series',
  },
  {
    id: 'birthdays',
    name: 'Birthdays',
    type: 'birthdays',
    enabled: true,
    capability: 'writable',
    visibility: { visibleByDefault: true, groupName: 'Household' },
    color: { hex: '#f97316' },
  },
] as const;

export const demoEvents: readonly NormalizedEvent[] = [
  {
    id: 'today-school-breakfast',
    sourceId: 'manual-events',
    title: 'Pack lunches and review school pickup plan',
    startsAt: '2026-06-18T07:30:00Z',
    endsAt: '2026-06-18T08:00:00Z',
    allDay: false,
    editable: true,
  },
  {
    id: 'today-holiday-reminder',
    sourceId: 'school-holidays',
    title: 'Teacher planning day',
    startsAt: '2026-06-18T00:00:00Z',
    allDay: true,
    editable: false,
    externalEventId: 'school-2026-06-18',
  },
  {
    id: 'tomorrow-family-call',
    sourceId: 'manual-events',
    title: 'Family planning call',
    startsAt: '2026-06-19T18:00:00Z',
    endsAt: '2026-06-19T18:45:00Z',
    allDay: false,
    editable: true,
  },
  {
    id: 'tomorrow-tv-premiere',
    sourceId: 'tv-series',
    title: 'Premiere night watch reminder',
    startsAt: '2026-06-19T20:00:00Z',
    endsAt: '2026-06-19T21:00:00Z',
    allDay: false,
    editable: false,
    externalEventId: 'tv-episode-1001',
  },
  {
    id: 'later-this-week-library',
    sourceId: 'manual-events',
    title: 'Library books due',
    startsAt: '2026-06-21T16:00:00Z',
    endsAt: '2026-06-21T16:15:00Z',
    allDay: false,
    editable: true,
  },
  {
    id: 'next-month-camp',
    sourceId: 'school-holidays',
    title: 'Summer camp registration confirmation day',
    startsAt: '2026-07-10T00:00:00Z',
    allDay: true,
    editable: false,
    externalEventId: 'school-2026-07-10',
  },
  {
    id: 'future-long-title',
    sourceId: 'manual-events',
    title: 'Quarterly household planning session with extended agenda title for layout validation',
    startsAt: '2026-08-15T10:00:00Z',
    endsAt: '2026-08-15T12:00:00Z',
    allDay: false,
    editable: true,
  },
  {
    id: 'future-tv-marathon',
    sourceId: 'tv-series',
    title: 'Season finale marathon',
    startsAt: '2026-09-05T19:30:00Z',
    endsAt: '2026-09-05T22:00:00Z',
    allDay: false,
    editable: false,
    externalEventId: 'tv-episode-2099',
  },
  {
    id: 'birthday-avery-20260620',
    sourceId: 'birthdays',
    title: 'Avery birthday',
    startsAt: '2026-06-20T00:00:00Z',
    endsAt: '2026-06-21T00:00:00Z',
    allDay: true,
    editable: false,
    externalEventId: 'avery',
  },
  {
    id: 'birthday-morgan-20260625',
    sourceId: 'birthdays',
    title: 'Morgan birthday',
    startsAt: '2026-06-25T00:00:00Z',
    endsAt: '2026-06-26T00:00:00Z',
    allDay: true,
    editable: false,
    externalEventId: 'morgan',
  },
  {
    id: 'birthday-riley-20261103',
    sourceId: 'birthdays',
    title: 'Riley birthday',
    startsAt: '2026-11-03T00:00:00Z',
    endsAt: '2026-11-04T00:00:00Z',
    allDay: true,
    editable: false,
    externalEventId: 'riley',
  },
  {
    id: 'birthday-casey-20270115',
    sourceId: 'birthdays',
    title: 'Casey birthday',
    startsAt: '2027-01-15T00:00:00Z',
    endsAt: '2027-01-16T00:00:00Z',
    allDay: true,
    editable: false,
    externalEventId: 'casey',
  },
] as const;
