import { cleanup, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { FloorPlanAssetAvailability, FloorPlanAssetState, FloorPlanReplacementReviewStatus, RoomReplacementDisposition, RoomType } from "../api/homeOpsApiClient";
import { FloorPlanReplacementReview } from "./FloorPlanReplacementReview";
import * as api from "./floorPlanReplacementReviewApi";

vi.mock("./floorPlanReplacementReviewApi", async (original) => ({ ...(await original<typeof import("./floorPlanReplacementReviewApi")>()), loadFloorPlanAssets: vi.fn(), getActiveReplacementReview: vi.fn(), listReplacementReviews: vi.fn(), getReplacementReviewRooms: vi.fn(), startReplacementReview: vi.fn(), updateReplacementRoomDisposition: vi.fn(), approveReplacementReuse: vi.fn(), attachReplacementOverlay: vi.fn(), validateReplacementReview: vi.fn(), activateReplacementReview: vi.fn(), cancelReplacementReview: vi.fn(), getReplacementRollbackAvailability: vi.fn(), rollbackReplacementReview: vi.fn() }));
const floor = { id: "f1", name: "Begane grond" } as any;
const rooms = [{ id: "r1", name: "Woonkamer", roomType: RoomType.LivingRoom }, { id: "r2", name: "Keuken", roomType: RoomType.Kitchen }] as any[];
const active = { id: "a1", state: FloorPlanAssetState.Active, derivativeAvailability: FloorPlanAssetAvailability.Available, derivativeUrl: "data:image/svg+xml,%3Csvg/%3E" } as any;
const replacement = { id: "a2", state: FloorPlanAssetState.Validated, replacementOfAssetId: "a1", derivativeAvailability: FloorPlanAssetAvailability.Available, derivativeUrl: "data:image/svg+xml,%3Csvg/%3E" } as any;
const review = { id: "rev1", status: FloorPlanReplacementReviewStatus.InReview, compatibility: { sameDerivativeBasis: true } } as any;
const items = [{ roomId: "r1", roomName: "Woonkamer", roomType: RoomType.LivingRoom, disposition: RoomReplacementDisposition.PendingReview, reuseCandidateAvailable: true }, { roomId: "r2", roomName: "Keuken", roomType: RoomType.Kitchen, disposition: RoomReplacementDisposition.BlockedFallback, fallbackReason: "lijst" }] as any[];
afterEach(() => cleanup());
beforeEach(() => { vi.clearAllMocks(); vi.mocked(api.loadFloorPlanAssets).mockResolvedValue([active, replacement]); vi.mocked(api.getActiveReplacementReview).mockResolvedValue(review); vi.mocked(api.listReplacementReviews).mockResolvedValue([]); vi.mocked(api.getReplacementReviewRooms).mockResolvedValue(items); vi.mocked(api.validateReplacementReview).mockResolvedValue({ isReady: false, blockers: [{ code: "PendingRooms" }] } as any); vi.mocked(api.getReplacementRollbackAvailability).mockResolvedValue({ isAvailable: true } as any); for (const fn of [api.startReplacementReview, api.updateReplacementRoomDisposition, api.approveReplacementReuse, api.attachReplacementOverlay, api.activateReplacementReview, api.cancelReplacementReview, api.rollbackReplacementReview]) vi.mocked(fn as any).mockResolvedValue({}); });
function setup() { return render(<FloorPlanReplacementReview floor={floor} rooms={rooms} activeAsset={active} onRefresh={vi.fn().mockResolvedValue(undefined)} />); }
describe("FloorPlanReplacementReview", () => {
  it("starts when no active review exists and handles no-active discovery", async () => { vi.mocked(api.getActiveReplacementReview).mockResolvedValue(null); vi.mocked(api.listReplacementReviews).mockResolvedValue([]); const user = userEvent.setup(); setup(); await screen.findByRole("button", { name: "Nieuwe plattegrond beoordelen" }); await user.click(screen.getByRole("button", { name: "Nieuwe plattegrond beoordelen" })); expect(screen.getByRole("dialog", { name: "Beoordeling starten" })).toBeTruthy(); await user.click(within(screen.getByRole("dialog")).getByRole("button", { name: "Beoordeling starten" })); await waitFor(() => expect(api.startReplacementReview).toHaveBeenCalledWith("f1", "a2")); });
  it("resumes review, maps statuses/dispositions, filters rooms and preserves failed disposition state", async () => { vi.mocked(api.updateReplacementRoomDisposition).mockRejectedValueOnce({ status: 400 }); const user = userEvent.setup(); setup(); await screen.findByText("Wordt beoordeeld"); expect(screen.getAllByText("Nog beoordelen").length).toBeGreaterThan(0); await user.click(screen.getByRole("tab", { name: "Fallback" })); expect(screen.getAllByText("Keuken").length).toBeGreaterThan(0); await user.click(screen.getByRole("tab", { name: "Alle kamers" })); await user.click(screen.getByLabelText("Niet op de plattegrond tonen")); await waitFor(() => expect(screen.getAllByRole("alert").some((el) => el.textContent?.includes("Keuze opslaan lukt niet"))).toBe(true)); expect(screen.getAllByText("Woonkamer").length).toBeGreaterThan(0); });
  it("approves reuse with anchor choice and exposes readiness blockers", async () => { const user = userEvent.setup(); setup(); await screen.findByText("Deze grens lijkt technisch herbruikbaar, maar moet nog handmatig worden gecontroleerd."); await user.click(screen.getByLabelText("Handmatige naampositie bewaren")); await user.click(screen.getByRole("button", { name: "Hergebruik goedkeuren" })); await waitFor(() => expect(api.approveReplacementReuse).toHaveBeenCalledWith("f1", "rev1", "r1", false)); expect(screen.getByRole("alert").textContent).toContain("Nog niet klaar"); });
  it("enables activation only when backend readiness is ready and preserves failure", async () => { vi.mocked(api.validateReplacementReview).mockResolvedValue({ isReady: true, blockers: [] } as any); vi.mocked(api.activateReplacementReview).mockRejectedValueOnce({ status: 400 }); const user = userEvent.setup(); setup(); await screen.findByRole("button", { name: "Nieuwe plattegrond activeren" }); expect((screen.getByRole("button", { name: "Nieuwe plattegrond activeren" }) as HTMLButtonElement).disabled).toBe(false); await user.click(screen.getByRole("button", { name: "Nieuwe plattegrond activeren" })); await user.click(within(screen.getByRole("dialog")).getByRole("button", { name: "Activeren" })); expect((await screen.findByRole("alert")).textContent).toContain("Activeren lukt niet"); });
  it("cancels active reviews and offers rollback for activated reviews", async () => { vi.mocked(api.getActiveReplacementReview).mockResolvedValue(null); vi.mocked(api.listReplacementReviews).mockResolvedValue([{ ...review, status: FloorPlanReplacementReviewStatus.Activated, rollbackAvailable: true } as any]); const user = userEvent.setup(); setup(); await screen.findByText("Geactiveerd"); expect(screen.queryByRole("button", { name: "Beoordeling annuleren" })).toBeNull(); await user.click(screen.getByRole("button", { name: "Vorige plattegrond herstellen" })); await user.click(within(screen.getByRole("dialog")).getByRole("button", { name: "Herstellen" })); await waitFor(() => expect(api.rollbackReplacementReview).toHaveBeenCalled()); });
});
