import { cleanup, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { RoomType } from "../api/homeOpsApiClient";
import { ClimateSourceRole, MappingHealth, ProviderType } from "./woningApi";
import { HomeAssistantClimateSettings } from "./HomeAssistantClimateSettings";
import * as api from "./woningApi";
vi.mock("./woningApi", async (importOriginal) => ({ ...(await importOriginal<typeof import("./woningApi")>()), loadClimateProviders: vi.fn(), loadRoomClimateMappings: vi.fn(), loadHomeAssistantDiagnostics: vi.fn(), saveHomeAssistantProvider: vi.fn(), refreshHomeAssistantProvider: vi.fn(), refreshHomeAssistantRoom: vi.fn(), refreshHomeAssistantMapping: vi.fn(), loadHomeAssistantResumeStrategy: vi.fn(), updateHomeAssistantResumeStrategy: vi.fn() }));
const rooms = [{ id: "r1", name: "Woonkamer", roomType: RoomType.LivingRoom }, { id: "r2", name: "Slaapkamer", roomType: RoomType.Bedroom }] as any;
const provider = { id: "p1", displayName: "HA Thuis", providerType: ProviderType.HomeAssistant, isEnabled: true, externalInstanceReference: "https://ha.local" } as any;
const mapping = { id: "m1", roomId: "r1", providerId: "p1", sourceRole: ClimateSourceRole.ComfortTemperature, health: MappingHealth.Healthy, isEnabled: true, source: { externalDisplayName: "Woonkamer temperatuur" }, diagnosticSummary: "Veilige diagnose", lastCheckedUtc: new Date("2026-07-17T10:00:00Z") } as any;
afterEach(() => cleanup());
beforeEach(() => { vi.clearAllMocks(); vi.mocked(api.loadClimateProviders).mockResolvedValue([provider]); vi.mocked(api.loadRoomClimateMappings).mockImplementation(async (roomId) => roomId === "r1" ? [mapping] : []); vi.mocked(api.loadHomeAssistantResumeStrategy).mockResolvedValue({ strategyType: 0, supportsResumeSchedule: false, blockers: [] } as any); vi.mocked(api.updateHomeAssistantResumeStrategy).mockResolvedValue({ strategyType: 1, supportsResumeSchedule: true, scriptEntityReference: "script.resume" } as any); vi.mocked(api.loadHomeAssistantDiagnostics).mockResolvedValue({ providerId: "p1", outcome: "Healthy", lastSuccessfulUtc: new Date("2026-07-17T10:05:00Z"), mappings: [] } as any); vi.mocked(api.saveHomeAssistantProvider).mockResolvedValue(provider); vi.mocked(api.refreshHomeAssistantProvider).mockResolvedValue({ outcome: 0, roomsAttempted: 2, roomsSucceeded: 2, roomsFailed: 0, mappingsHealthy: 1, observationsAccepted: 1 } as any); vi.mocked(api.refreshHomeAssistantRoom).mockResolvedValue({ outcome: 0 } as any); vi.mocked(api.refreshHomeAssistantMapping).mockResolvedValue({ outcome: 0 } as any); });
describe("HomeAssistantClimateSettings", () => {
  it("shows empty setup, credential guidance, and rejects embedded credentials", async () => { vi.mocked(api.loadClimateProviders).mockResolvedValueOnce([]); vi.mocked(api.loadRoomClimateMappings).mockResolvedValue([]); const user = userEvent.setup(); render(<HomeAssistantClimateSettings rooms={rooms} />); await screen.findByText("Home Assistant is nog niet ingesteld."); expect(screen.getByText(/HOMEASSISTANT__ACCESSTOKEN/)).toBeTruthy(); await user.click(screen.getByRole("button", { name: "Home Assistant toevoegen" })); await user.clear(screen.getByLabelText("Home Assistant-adres")); await user.type(screen.getByLabelText("Home Assistant-adres"), "https://user:secret@ha.local"); expect(screen.getByRole("alert").textContent).toContain("geen gebruikersnaam"); expect(screen.queryByText("secret-token")).toBeNull(); });
  it("shows provider summary, safe diagnostics, mappings and refresh actions", async () => { const user = userEvent.setup(); render(<HomeAssistantClimateSettings rooms={rooms} />); await screen.findByText("HA Thuis"); expect(screen.getByText("Verbinding met Home Assistant is gelukt.")).toBeTruthy(); expect(screen.getByText("Kamertemperatuur")).toBeTruthy(); expect(screen.getByText(/In orde/)).toBeTruthy(); expect(screen.getByText("Veilige diagnose")).toBeTruthy(); expect(screen.queryByText(/Authorization/i)).toBeNull(); await user.click(screen.getByRole("button", { name: "Verbinding controleren" })); await waitFor(() => expect(api.refreshHomeAssistantProvider).toHaveBeenCalledWith("p1")); expect(await screen.findByText(/Kamers: 2\/2 gelukt/)).toBeTruthy(); });
  it("saves safe provider fields", async () => { const user = userEvent.setup(); render(<HomeAssistantClimateSettings rooms={rooms} />); await screen.findByText("HA Thuis"); await user.click(screen.getByRole("button", { name: "Home Assistant beheren" })); await user.clear(screen.getByLabelText("Weergavenaam")); await user.type(screen.getByLabelText("Weergavenaam"), "Home Assistant nieuw"); await user.click(within(screen.getByRole("dialog", { name: "Home Assistant beheren" })).getByRole("button", { name: "Opslaan" })); expect(api.saveHomeAssistantProvider).toHaveBeenCalledWith(provider, "Home Assistant nieuw", "https://ha.local", true); });
  it("configures typed resume strategies without service or JSON editors", async () => { const user = userEvent.setup(); render(<HomeAssistantClimateSettings rooms={rooms} />); await screen.findByText("Schema hervatten"); await user.click(screen.getByLabelText("Home Assistant-script gebruiken")); await user.type(screen.getByLabelText("Script-entiteit"), "script.resume"); await user.click(screen.getByRole("button", { name: "Hervatmethode opslaan" })); await waitFor(() => expect(api.updateHomeAssistantResumeStrategy).toHaveBeenCalled()); expect(screen.queryByLabelText(/service/i)).toBeNull(); expect(screen.queryByLabelText(/json/i)).toBeNull(); expect(screen.queryByLabelText(/token/i)).toBeNull(); });
});
