import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { FloorPlanAssetAvailability, FloorPlanAssetState, RoomOverlayState, RoomType } from "../api/homeOpsApiClient";
import { WoningManagement } from "./WoningManagement";
import * as woningApi from "./woningApi";
import * as overlayApi from "./roomOverlayEditorApi";

vi.mock("./woningApi", async (importOriginal) => ({ ...(await importOriginal<typeof import("./woningApi")>()), loadFloors: vi.fn(), loadRooms: vi.fn(), loadClimateConfiguration: vi.fn(), createFloor: vi.fn(), updateFloor: vi.fn(), reorderFloors: vi.fn(), archiveFloor: vi.fn(), restoreFloor: vi.fn(), deleteFloor: vi.fn(), createRoom: vi.fn(), updateRoom: vi.fn(), reorderRooms: vi.fn(), moveRoom: vi.fn(), archiveRoom: vi.fn(), restoreRoom: vi.fn(), deleteRoom: vi.fn() }));
vi.mock("./roomOverlayEditorApi", async (importOriginal) => ({ ...(await importOriginal<typeof import("./roomOverlayEditorApi")>()), loadActiveFloorPlanAsset: vi.fn(), loadFloorRoomOverlays: vi.fn(), createRoomOverlay: vi.fn(), updateRoomOverlayGeometry: vi.fn(), updateRoomOverlayLabelAnchor: vi.fn(), resetRoomOverlayLabelAnchor: vi.fn(), trustRoomOverlay: vi.fn(), markRoomOverlayNeedsReview: vi.fn(), archiveRoomOverlay: vi.fn(), restoreRoomOverlay: vi.fn(), deleteRoomOverlay: vi.fn() }));
const floors = [{ id: "f1", name: "Begane grond", sortOrder: 0, activeRoomCount: 2 }];
const rooms = [{ id: "r1", floorId: "f1", name: "Woonkamer", roomType: RoomType.LivingRoom, sortOrder: 0 }, { id: "r2", floorId: "f1", name: "Keuken", roomType: RoomType.Kitchen, sortOrder: 1 }];
const asset = { id: "a1", floorId: "f1", state: FloorPlanAssetState.Active, derivativeAvailability: FloorPlanAssetAvailability.Available, derivativeUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'/%3E" } as any;
afterEach(() => cleanup());
beforeEach(() => {
  vi.clearAllMocks();
  window.matchMedia = vi.fn().mockReturnValue({ matches: false, addEventListener: vi.fn(), removeEventListener: vi.fn() }) as any;
  vi.mocked(woningApi.loadFloors).mockResolvedValue(floors as any);
  vi.mocked(woningApi.loadRooms).mockResolvedValue(rooms as any);
  vi.mocked(woningApi.loadClimateConfiguration).mockResolvedValue(null as any);
  vi.mocked(overlayApi.loadActiveFloorPlanAsset).mockResolvedValue(asset);
  vi.mocked(overlayApi.loadFloorRoomOverlays).mockResolvedValue([
    { id: "o2", roomId: "r2", floorPlanAssetId: "a1", state: RoomOverlayState.Trusted, polygon: [{ x: .7, y: .1 }, { x: .9, y: .1 }, { x: .9, y: .4 }, { x: .7, y: .4 }] as any, validationBlockerCount: 0, validationWarningCount: 0 },
    { id: "oa", roomId: "r1", floorPlanAssetId: "a1", state: RoomOverlayState.Archived, polygon: [{ x: .1, y: .1 }, { x: .2, y: .1 }, { x: .2, y: .2 }] as any },
  ] as any);
  for (const fn of [overlayApi.createRoomOverlay, overlayApi.updateRoomOverlayGeometry, overlayApi.updateRoomOverlayLabelAnchor, overlayApi.resetRoomOverlayLabelAnchor, overlayApi.trustRoomOverlay, overlayApi.markRoomOverlayNeedsReview, overlayApi.archiveRoomOverlay, overlayApi.restoreRoomOverlay, overlayApi.deleteRoomOverlay]) vi.mocked(fn as any).mockResolvedValue({});
});
async function openEditor() { render(<WoningManagement />); await screen.findByText("Woningoverzicht is bijgewerkt."); await userEvent.click(screen.getByRole("button", { name: "Kamergrenzen tekenen" })); await screen.findByRole("heading", { name: "Kamers" }); }
describe("RoomOverlayEditor", () => {
  it("opens from Settings with an active safe asset, shows statuses and archived overlays", async () => { await openEditor(); expect(screen.getByText(/Plattegrond inrichten/)).toBeTruthy(); expect(screen.getByText("Nog geen grens")).toBeTruthy(); expect(screen.getByText("Klaar voor gebruik")).toBeTruthy(); expect(screen.getByText("Gearchiveerde grenzen")).toBeTruthy(); });
  it("blocks editor entry when no active asset exists", async () => { vi.mocked(overlayApi.loadActiveFloorPlanAsset).mockResolvedValueOnce(null); render(<WoningManagement />); await screen.findByText("Woningoverzicht is bijgewerkt."); expect(screen.queryByRole("button", { name: "Kamergrenzen tekenen" })).toBeNull(); expect(screen.getByText(/Er is nog geen bruikbare plattegrond/)).toBeTruthy(); });
  it("draws, validates, closes, saves draft and valid while retaining geometry after failed save", async () => { vi.mocked(overlayApi.createRoomOverlay).mockRejectedValueOnce({ status: 500 }).mockResolvedValueOnce({} as any); await openEditor(); await userEvent.click(screen.getByRole("button", { name: "Grens tekenen" })); const svg = screen.getByLabelText(/Plattegrondcanvas/); Object.defineProperty(svg, "getBoundingClientRect", { value: () => ({ left: 0, top: 0, width: 100, height: 100 }) }); fireEvent.pointerDown(svg, { clientX: 10, clientY: 10 }); fireEvent.pointerDown(svg, { clientX: 50, clientY: 10 }); expect(screen.getByText("Plaats minimaal drie punten.")).toBeTruthy(); fireEvent.pointerDown(svg, { clientX: 50, clientY: 50 }); await userEvent.keyboard("{Enter}"); await userEvent.click(screen.getByRole("button", { name: "Concept opslaan" })); expect(await screen.findByText(/Je tekening blijft staan/)).toBeTruthy(); expect(svg.querySelectorAll("circle.overlay-handle").length).toBe(3); await userEvent.click(screen.getByRole("button", { name: "Grens opslaan" })); expect(overlayApi.createRoomOverlay).toHaveBeenLastCalledWith("f1", "r1", "a1", expect.any(Array), RoomOverlayState.Valid, undefined); });
  it("supports rectangle helper, label anchor and lifecycle actions", async () => { vi.mocked(overlayApi.loadFloorRoomOverlays).mockResolvedValue([{ id: "o1", roomId: "r1", floorPlanAssetId: "a1", state: RoomOverlayState.Valid, polygon: ([{ x: .1, y: .1 }, { x: .4, y: .1 }, { x: .4, y: .4 }, { x: .1, y: .4 }] as any) }] as any); await openEditor(); await userEvent.click(screen.getByRole("button", { name: "Rechthoek tekenen" })); expect(screen.getByText("Niet-opgeslagen wijzigingen")).toBeTruthy(); await userEvent.click(screen.getByRole("button", { name: "Kamernaam plaatsen" })); const svg = screen.getByLabelText(/Plattegrondcanvas/); Object.defineProperty(svg, "getBoundingClientRect", { value: () => ({ left: 0, top: 0, width: 100, height: 100 }) }); fireEvent.pointerDown(svg, { clientX: 30, clientY: 30 }); await userEvent.click(screen.getByRole("button", { name: "Grens opslaan" })); await waitFor(() => expect(overlayApi.updateRoomOverlayGeometry).toHaveBeenCalled()); expect(overlayApi.updateRoomOverlayLabelAnchor).toHaveBeenCalled(); await userEvent.click(screen.getByRole("button", { name: "Klaar voor gebruik maken" })); expect(overlayApi.trustRoomOverlay).toHaveBeenCalledWith("o1"); await userEvent.click(screen.getByRole("button", { name: "Opnieuw controleren" })); expect(overlayApi.markRoomOverlayNeedsReview).toHaveBeenCalledWith("o1"); await userEvent.click(screen.getByRole("button", { name: "Archiveren" })); expect(overlayApi.archiveRoomOverlay).toHaveBeenCalledWith("o1"); });
  it("synchronizes list selection and shows phone limitation", async () => { window.matchMedia = vi.fn().mockReturnValue({ matches: true, addEventListener: vi.fn(), removeEventListener: vi.fn() }) as any; await openEditor(); expect(screen.getByText("Kamergrenzen tekenen werkt beter op een groter scherm.")).toBeTruthy(); await userEvent.click(screen.getByRole("listitem", { name: /Keuken/ })); expect(screen.getAllByText("Keuken").length).toBeGreaterThan(0); });
});
