import { cleanup, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { RoomType } from "../api/homeOpsApiClient";
import { WoningManagement } from "./WoningManagement";
import * as api from "./woningApi";

vi.mock("./woningApi", async (importOriginal) => ({ ...(await importOriginal<typeof import("./woningApi")>()), loadFloors: vi.fn(), loadRooms: vi.fn(), loadClimateConfiguration: vi.fn(), createFloor: vi.fn(), updateFloor: vi.fn(), reorderFloors: vi.fn(), archiveFloor: vi.fn(), restoreFloor: vi.fn(), deleteFloor: vi.fn(), createRoom: vi.fn(), updateRoom: vi.fn(), reorderRooms: vi.fn(), moveRoom: vi.fn(), archiveRoom: vi.fn(), restoreRoom: vi.fn(), deleteRoom: vi.fn(), loadClimateProviders: vi.fn(), loadRoomClimateMappings: vi.fn(), loadHomeAssistantDiagnostics: vi.fn(), saveHomeAssistantProvider: vi.fn(), refreshHomeAssistantProvider: vi.fn(), refreshHomeAssistantRoom: vi.fn(), refreshHomeAssistantMapping: vi.fn(), loadHomeAssistantResumeStrategy: vi.fn(), updateHomeAssistantResumeStrategy: vi.fn() }));
const floors = [{ id: "f1", name: "Begane grond", sortOrder: 0, activeRoomCount: 2 }, { id: "f2", name: "Eerste verdieping", sortOrder: 1, activeRoomCount: 1 }, { id: "fa", name: "Zolder oud", sortOrder: 2, activeRoomCount: 0, isArchived: true }];
const rooms: Record<string, any[]> = { f1: [{ id: "r1", floorId: "f1", name: "Woonkamer", roomType: RoomType.LivingRoom, sortOrder: 0 }, { id: "r2", floorId: "f1", name: "Keuken", roomType: RoomType.Kitchen, sortOrder: 1, familyMember: { id: "m1", name: "Sam" } }, { id: "ra", floorId: "f1", name: "Bijkeuken", roomType: RoomType.UtilityRoom, sortOrder: 2, isArchived: true }], f2: [{ id: "r3", floorId: "f2", name: "Slaapkamer", roomType: RoomType.Bedroom, sortOrder: 0 }], fa: [] };
afterEach(() => cleanup());
beforeEach(() => { vi.clearAllMocks(); vi.mocked(api.loadFloors).mockResolvedValue(floors as any); vi.mocked(api.loadRooms).mockImplementation(async (id) => rooms[id] ?? []); vi.mocked(api.loadClimateProviders).mockResolvedValue([] as any); vi.mocked(api.loadRoomClimateMappings).mockResolvedValue([] as any); vi.mocked(api.loadHomeAssistantResumeStrategy).mockResolvedValue({ strategyType: 0, supportsResumeSchedule: false, blockers: [] } as any); vi.mocked(api.updateHomeAssistantResumeStrategy).mockResolvedValue({ strategyType: 1, supportsResumeSchedule: true, scriptEntityReference: "script.resume" } as any); vi.mocked(api.loadHomeAssistantDiagnostics).mockResolvedValue(null as any); vi.mocked(api.saveHomeAssistantProvider).mockResolvedValue({} as any); vi.mocked(api.refreshHomeAssistantProvider).mockResolvedValue({} as any); vi.mocked(api.refreshHomeAssistantRoom).mockResolvedValue({} as any); vi.mocked(api.refreshHomeAssistantMapping).mockResolvedValue({} as any); vi.mocked(api.loadClimateConfiguration).mockImplementation(async (id) => id === "r1" ? ({ isConfigured: true, isClimateEnabled: true, isBedtimeRelevant: true } as any) : null); for (const fn of [api.createFloor, api.updateFloor, api.reorderFloors, api.archiveFloor, api.restoreFloor, api.deleteFloor, api.createRoom, api.updateRoom, api.reorderRooms, api.moveRoom, api.archiveRoom, api.restoreRoom, api.deleteRoom]) vi.mocked(fn as any).mockResolvedValue({}); });

describe("WoningManagement", () => {
  it("shows floors, rooms, Dutch room type labels, family members and summaries", async () => { render(<WoningManagement members={[{ id: "m1", name: "Sam" } as any]} />); await screen.findByText("Woningoverzicht is bijgewerkt."); expect(screen.getAllByText("Begane grond").length).toBeGreaterThan(0); expect(screen.getByText("Nog geen plattegrond")).toBeTruthy(); expect(screen.getByText(/Keuken · Sam/)).toBeTruthy(); expect(screen.getByText("Bedtijd meegenomen")).toBeTruthy(); expect(screen.getByLabelText("Gearchiveerde verdiepingen").textContent).toContain("Zolder oud"); expect(screen.getByLabelText("Gearchiveerde kamers").textContent).toContain("Bijkeuken"); });
  it("creates floors and rooms and supports optional family member clearing", async () => { const user = userEvent.setup(); render(<WoningManagement members={[{ id: "m1", name: "Sam" } as any]} />); await screen.findByText("Woningoverzicht is bijgewerkt."); await user.click(screen.getByRole("button", { name: "Verdieping toevoegen" })); await user.type(screen.getByLabelText("Naam verdieping"), "Kelder"); await user.click(within(screen.getByRole("dialog", { name: "Verdieping toevoegen" })).getByRole("button", { name: "Verdieping toevoegen" })); expect(api.createFloor).toHaveBeenCalledWith("Kelder"); await waitFor(() => expect(screen.queryByRole("dialog")).toBeNull()); await user.click(screen.getByRole("button", { name: "Kamer toevoegen" })); await user.type(screen.getByLabelText("Naam kamer"), "Logeerkamer"); await user.selectOptions(screen.getByLabelText("Kamertype"), String(RoomType.Bedroom)); await user.selectOptions(screen.getByLabelText("Gezinslid (optioneel)"), "m1"); await user.selectOptions(screen.getByLabelText("Gezinslid (optioneel)"), ""); await user.click(within(screen.getByRole("dialog", { name: "Kamer toevoegen" })).getByRole("button", { name: "Kamer toevoegen" })); expect(api.createRoom).toHaveBeenCalledWith("f1", "Logeerkamer", RoomType.Bedroom, undefined); });
  it("uses accessible reorder controls and moves rooms between floors", async () => { const user = userEvent.setup(); render(<WoningManagement />); await screen.findByText("Woningoverzicht is bijgewerkt."); await user.click(within(screen.getAllByText("Begane grond")[0].closest("article")!).getByRole("button", { name: "Onderaan" })); expect(api.reorderFloors).toHaveBeenCalledWith(["f2", "f1"]); await user.click(within(screen.getAllByText("Woonkamer")[0].closest("article")!).getByRole("button", { name: "Verplaatsen" })); expect(screen.getByRole("dialog", { name: "Kamer verplaatsen" })).toBeTruthy(); await user.click(within(screen.getByRole("dialog", { name: "Kamer verplaatsen" })).getByRole("button", { name: "Verplaatsen" })); expect(api.moveRoom).toHaveBeenCalledWith("r1", "f2"); });
  it("surfaces archive blocked, delete, restore, loading and error states", async () => { vi.mocked(api.archiveFloor).mockRejectedValueOnce({ status: 409 }); const user = userEvent.setup(); render(<WoningManagement />); await screen.findByText("Woningoverzicht is bijgewerkt."); await user.click(within(screen.getAllByText("Begane grond")[0].closest("article")!).getByRole("button", { name: "Archiveren" })); expect(screen.getByText("Deze verdieping kan nog niet worden gearchiveerd omdat er kamers in staan.")).toBeTruthy(); await user.click(within(screen.getByRole("dialog", { name: "Verdieping archiveren" })).getByRole("button", { name: "Archiveren" })); expect((await screen.findByRole("alert")).textContent).toContain("Deze verdieping kan nog niet worden gearchiveerd omdat er kamers in staan."); await user.click(screen.getByText("Herstellen: Zolder oud")); expect(api.restoreFloor).toHaveBeenCalledWith("fa"); });
});
