namespace HomeOps.Api.CalendarEvents.ICalendar;

public sealed record NormalizedICalendarEvent(
    string ProviderEventId,
    string? ProviderRevision,
    string ContentFingerprint,
    string Title,
    string? Description,
    string? Location,
    DateOnly StartDate,
    TimeOnly? StartTime,
    DateOnly EndDate,
    TimeOnly? EndTime,
    bool IsAllDay,
    DateTime? CreatedUtc,
    DateTime? LastModifiedUtc,
    int Sequence,
    string? Status,
    string? Transparency,
    RecurrenceType RecurrenceType,
    string? RawRecurrenceRule,
    EventRecurrenceRule? RecurrenceRule = null,
    IReadOnlyList<NormalizedICalendarEventException>? Exceptions = null);

public sealed record NormalizedICalendarEventException(
    OccurrenceKey OccurrenceKey,
    EventExceptionType ExceptionType,
    string? Title = null,
    string? Description = null,
    string? Location = null,
    bool? IsAllDay = null,
    DateOnly? StartDate = null,
    TimeOnly? StartTime = null,
    DateOnly? EndDate = null,
    TimeOnly? EndTime = null,
    string? RawProviderRecurrenceId = null,
    string? NormalizedProviderRecurrenceId = null,
    string? DetachedProviderEventId = null,
    string? DetachedProviderRevision = null,
    string? DetachedContentFingerprint = null,
    string? RawDetachedRecurrenceMetadata = null);
